
% Supporting Information for Nighttime aircraft intercepts of biomass burning plumes: observations and box model analysis
% 
% Zachary C. J. Decker, Kyle J. Zarzana1, Matthew Coggon1, Kyung-Eun Min1, Ilana Pollack1, Thomas B. Ryerson, Jeff Peischl, Peter Edwards, William P. Dub?, Milos Z. Markovic1, James M. Roberts1, Patrick R. Veres, Martin Graus, Carsten Warneke1, Joost de Gouw, Lindsay E. Hatch, Kelley C. Barsanti, Steven S. Brown
% 
% Lixu- In order to be consistent with Matt Coggon's codes, we 1)replace
% MFURFURAL with MEFURFURAL, DM25FURAN with DIMEFURAN. 2) delete repeating
% reactions(FURAN + OH; DIMEFURAN + OH; M3F+OH/NO3/O3; MEFURFURAL + OH; M2FURAN + OH)
% 3) assume FURFURAL2 in the raw script is FURFURAL in Coggon's codes and
% replace FURFURAL2 with FURFURAL, based on Coggon's slide.
% 4) delete those tracer reactions just in case.
% 5) delete repeated GUAIACOL + NO3 = NR1GUAIACOL reactions.

% ---- Begin F0AM Add Compounds code ----
 
%% Compound list
SpeciesToAdd = {...
'ACECN';'ACENAP';'ACETNH';'ACETOL';'ACO2H';'AeroNO3';
'AeroSA';'ALLYLOH';'ANSIOL';'APHELLANDRENE';'APINENE';
'BCARY';'BENZACETCN';'BENZCN';'BENZENE';'BENZHEX';'BENZNO2';
'BENZPENT';'BIACET';'BIPHENYL';'BMYRCENE';'BPHELLANDRENE';
'BPINENE';'BUT2OLO';'BUTADIENE';'BUTANCN';'BUTE2AL';
'BUTENAL2';'BUTENCN';'BUTENNO3';'BZFUONE';'C10ARO';
'C2H2';'C2H3CN';'C2H5N';'C2H5OH';'C3FURANS';'C3MDBAL';
'C3PYRROLE';'C4H4';'C4MDIAL';'C5H6';'C5H8';'C6CO34';
'C6ESTERS';'C7ACRYCN';'C7HEXENES';'C8HEPTENE';'CAMPHENE';
'CAMPHOR';'CARENE3';'CATECHOL';'CH3CO2H';'CH3COCH3';
'CH3COCO2H';'CH3NO2';'CH3OH';'CHCCOOH';'CINEOLE';'ClNO2';
'CO23C5';'CO23C6';'CO24C6';'CO25C6';'CRESOL';'CYHEX13DIEN';
'CYHEXENE';'CYHEXONE';'CYPENT2EN14DION';'CYPENT2EN1ON';
'CYPENT3EN12DION';'CYPENT3EN1ON';'CYPENTDIONE';'CYPENTENE';
'CYPENTONE';'DEC19DIEN';'DEC1EN';'DECANAL';'DHYPYRROLE';
'DIEK';'DIFURANDIONE';'DIHYDOXYPYR';'DIHYMFUR';'DIHYNAP';
'DIHYPYRD';'DIMDISIDE';'DIMNAP';'DIMPHEN';'DIMPYRROLE';
'DIMPYRS';'DM23BU2ENE';'DM23BUT13DIEN';'DIMEFURAN';
'DM25HEX1EN';'DM34CYPENTEN1ONE';'DM35CYPENTEN';'DM44CYHEPTEN';
'DODEC111DIEN';'DODEC1EN';'E1PREK';'E2PREK';'ESTRAGOLE';
'ETCYPENTONE';'ETENCYPENT';'ETH1M3BENZ';'ETHACROL';
'ETHENCYHEX';'ETHENNO2';'ETHFORM';'ETHFURAN2';'ETHLIINDANE';
'ETHPYRS';'ETHSYTRENE';'ETPYRROLE';'ETYNPYRROLE';'EVK';
'EZOCIMENE';'FURAN';'FURAN23DIHYD';'FURAN25DIHYD';'FURANTETHYD';
'FURCARBCN2';'FURCARBCN3';'FURFUR3AL';'FURFURAL';'FURFURAL3';
'GUAIACOL';'H2S';'HCN';'HCONH2';'HCOOH';'HEPT16DIEN';
'HEPT3ONE';'HEPTCNS';'HEPTEN';'HEX13DIEN';'HEX14DIEN';
'HEX15DI3YN';'HEX1EN3YN';'HEX2EN4YN';'HEX2ENE';'HEX2ONE';
'HEX3ONE';'HEX3YN';'HEXE14DIEN';'HEXEE24DIEN';'HEXEE24DIENAL';
'HEXEX24DIEN';'HNCO';'HNO3';'HONO';'HYBENZQUIN';'HYDROXCN';
'INDANE';'INDENE';'IPROPOL';'ISOBUTCN';'ISOEUGOL';'LIMONENE';
'M1CYHEXEN';'M1CYPENEN';'M1CYPENT13DIEN';'M2BK';'M2BUT1EN3YN';
'M2BUTANAL';'M2BUTCN';'M2CYPENT2EN1ON';'M2CYPENTON';
'M2FURAN';'M2OLFURAN';'M2PENT14DIEN';'M2PENT2EN';'M2PENTE13DIEN';
'M2PENTZ13DIEN';'M3BUTCN';'M3CO5C6';'M3CYHEXEN';'M3CYPENT2EN1ON';
'M3CYPENTEN';'M3ETH2BUT1EN';'M3F';'M3PENTE2EN';'M3PENTZ13DIEN';
'M3PENTZ2EN';'M4CYHEX4EN';'M4PENT13DIEN';'M4PENT1EN';
'M5CYPENT13DIEN';'M5FURAN23DIHY';'M5PENT2EN';'MACRYLATE';
'MACRYLCN';'MANIMINE';'MANISOLE';'MBENZACETO';'MBENZAL';
'MCHAVICOL';'MCYPENTONES';'MEK';'MEKCOH';'MESTPROPACD';
'METHACET';'MEFURFURAL';'MGUAIACOL';'MIBK';'MIPK';'MMALANHY';
'MMALIDE';'MMETACRL';'MNAPT';'MOXYHYFUR';'MPENTCN';
'MPHCOME';'MPRK';'MPROPBENZ';'MPROPOATE';'MPYRIDINE2';
'MPYRIDINE3';'MPYRROLE';'MSTYRENE';'MTHIOL';'MTHIOPHENE';
'MVK';'MXYLCO2H';'N2O5';'N3SYRINGOL';'N4GUAIACOL';'N6GUAIACOL';
'N6MGUAIACOL';'NAPT';'NBUTACET';'NBUTOL';'NH3';'NO2';
'NO3';'NON18DIEN';'NONEN';'NPROACET';'NR12GUAIACOL';
'NR14GUAIACOL';'NR1GUAIACOL';'NR34SYRINGOL';'NR4SYRINGOL';
'NR56MGUAIACOL';'NR5MGUAIACOL';'O3';'OCT17DIEN';'OCTENES';
'OH';'OTHFURAN';'OTHMONOT';'OXNO3APHELLANDRENE';'OXNO3APINENE';
'OXNO3BCARY';'OXNO3BMYRCENE';'OXNO3BPHELLANDRENE';'OXNO3BPINENE';
'OXNO3BZFUONE';'OXNO3C3FURANS';'OXNO3C3PYRROLE';'OXNO3C5H6';
'OXNO3C5H8';'OXNO3CARENE3';'OXNO3CATECHOL';'OXNO3CRESOL';
'OXNO3CYHEX13DIEN';'OXNO3DHYPYRROLE';'OXNO3DIHYMFUR';
'OXNO3DIMNAP';'OXNO3DIMPHEN';'OXNO3DIMPYRROLE';'OXNO3DM23BU2ENE';
'OXNO3DIMEFURAN';'OXNO3ETHFURAN2';'OXNO3ETPYRROLE';
'OXNO3EZOCIMENE';'OXNO3FURAN';'OXNO3FURAN23DIHYD';'OXNO3FURAN25DIHYD';
'OXNO3FURFURAL';'OXNO3FURFURAL3';'OXNO3GUAIACOL';'OXNO3INDENE';
'OXNO3LIMONENE';'OXNO3M1CYPENEN';'OXNO3M1CYPENT13DIEN';
'OXNO3M2FURAN';'OXNO3M2OLFURAN';'OXNO3M2PENT2EN';'OXNO3M2PENTZ13DIEN';
'OXNO3M3CYHEXEN';'OXNO3M3F';'OXNO3M5CYPENT13DIEN';'OXNO3M5FURAN23DIHY';
'OXNO3MEFURFURAL';'OXNO3MGUAIACOL';'OXNO3MNAPT';'OXNO3MPYRROLE';
'OXNO3NAPT';'OXNO3OTHFURAN';'OXNO3OTHMONOT';'OXNO3OXYFUR';
'OXNO3OXYMCYPENONE';'OXNO3OXYMFUR';'OXNO3PENTE13DIEN';
'OXNO3PENTZ13DIEN';'OXNO3PHENOL';'OXNO3PYRROLE';'OXNO3SALAL';
'OXNO3SYRINGOL';'OXNO3TERPINOLENE';'OXNO3VANILIN';'OXNO3VGUAIACOL';
'OXO3APHELLANDRENE';'OXO3APINENE';'OXO3BCARY';'OXO3BMYRCENE';
'OXO3BPHELLANDRENE';'OXO3BPINENE';'OXO3BZFUONE';'OXO3C3FURANS';
'OXO3C3PYRROLE';'OXO3C5H6';'OXO3C5H8';'OXO3CARENE3';
'OXO3CATECHOL';'OXO3CRESOL';'OXO3CYHEX13DIEN';'OXO3DHYPYRROLE';
'OXO3DIHYMFUR';'OXO3DIMNAP';'OXO3DIMPHEN';'OXO3DIMPYRROLE';
'OXO3DM23BU2ENE';'OXO3DIMEFURAN';'OXO3ETHFURAN2';'OXO3ETPYRROLE';
'OXO3EZOCIMENE';'OXO3FURAN';'OXO3FURAN23DIHYD';'OXO3FURAN25DIHYD';
'OXO3FURFURAL';'OXO3FURFURAL3';'OXO3GUAIACOL';'OXO3INDENE';
'OXO3LIMONENE';'OXO3M1CYPENEN';'OXO3M1CYPENT13DIEN';
'OXO3M2FURAN';'OXO3M2OLFURAN';'OXO3M2PENT2EN';'OXO3M2PENTZ13DIEN';
'OXO3M3CYHEXEN';'OXO3M3F';'OXO3M5CYPENT13DIEN';'OXO3M5FURAN23DIHY';
'OXO3MEFURFURAL';'OXO3MGUAIACOL';'OXO3MNAPT';'OXO3MPYRROLE';
'OXO3NAPT';'OXO3OTHFURAN';'OXO3OTHMONOT';'OXO3OXYFUR';
'OXO3OXYMCYPENONE';'OXO3OXYMFUR';'OXO3PENTE13DIEN';
'OXO3PENTZ13DIEN';'OXO3PHENOL';'OXO3PYRROLE';'OXO3SALAL';
'OXO3SYRINGOL';'OXO3TERPINOLENE';'OXO3VANILIN';'OXO3VGUAIACOL';
'OXOHAPHELLANDRENE';'OXOHAPINENE';'OXOHBCARY';'OXOHBMYRCENE';
'OXOHBPHELLANDRENE';'OXOHBPINENE';'OXOHBZFUONE';'OXOHC3FURANS';
'OXOHC3PYRROLE';'OXOHC5H6';'OXOHC5H8';'OXOHCARENE3';
'OXOHCATECHOL';'OXOHCRESOL';'OXOHCYHEX13DIEN';'OXOHDHYPYRROLE';
'OXOHDIHYMFUR';'OXOHDIMNAP';'OXOHDIMPHEN';'OXOHDIMPYRROLE';
'OXOHDM23BU2ENE';'OXOHDIMEFURAN';'OXOHETHFURAN2';'OXOHETPYRROLE';
'OXOHEZOCIMENE';'OXOHFURAN';'OXOHFURAN23DIHYD';'OXOHFURAN25DIHYD';
'OXOHFURFURAL';'OXOHFURFURAL3';'OXOHGUAIACOL';'OXOHINDENE';
'OXOHLIMONENE';'OXOHM1CYPENEN';'OXOHM1CYPENT13DIEN';
'OXOHM2FURAN';'OXOHM2OLFURAN';'OXOHM2PENT2EN';'OXOHM2PENTZ13DIEN';
'OXOHM3CYHEXEN';'OXOHM3F';'OXOHM5CYPENT13DIEN';'OXOHM5FURAN23DIHY';
'OXOHMEFURFURAL';'OXOHMGUAIACOL';'OXOHMNAPT';'OXOHMPYRROLE';
'OXOHNAPT';'OXOHOTHFURAN';'OXOHOTHMONOT';'OXOHOXYFUR';
'OXOHOXYMCYPENONE';'OXOHOXYMFUR';'OXOHPENTE13DIEN';
'OXOHPENTZ13DIEN';'OXOHPHENOL';'OXOHPYRROLE';'OXOHSALAL';
'OXOHSYRINGOL';'OXOHTERPINOLENE';'OXOHVANILIN';'OXOHVGUAIACOL';
'OXYFUR';'OXYLCO2H';'OXYMCYPENONE';'OXYMFUR';'OXYMFURONE';
'OXYMOHFURAN';'OXYMONTS';'OXYTETFUR';'PENT14DIEN';'PENT1EN1YN';
'PENT1YN';'PENT2ENE';'PENT4EN1YN';'PENTANCN';'PENTCN';
'PENTDENCN';'PENTE13DIEN';'PENTE2ENAL';'PENTE3EN1YN';
'PENTEN4AL';'PENTONE';'PENTZ13DIEN';'PENTZ3EN1YN';'PHACETLY';
'PHCOME';'PHEN4BUT3EN1YN';'PHENOL';'PO3APHELLANDRENE';
'PO3BMYRCENE';'PO3BPHELLANDRENE';'PO3C3FURANS';'PO3C3PYRROLE';
'PO3C5H6';'PO3CARENE3';'PO3CRESOL';'PO3CYHEX13DIEN';
'PO3DHYPYRROLE';'PO3DIHYMFUR';'PO3DIMNAP';'PO3DIMPHEN';
'PO3DIMPYRROLE';'PO3DIMEFURAN';'PO3ETHFURAN2';'PO3ETPYRROLE';
'PO3EZOCIMENE';'PO3FURAN';'PO3FURAN23DIHYD';'PO3FURAN25DIHYD';
'PO3FURFURAL';'PO3FURFURAL3';'PO3GUAIACOL';'PO3INDENE';
'PO3M1CYPENEN';'PO3M1CYPENT13DIEN';'PO3M2FURAN';'PO3M2OLFURAN';
'PO3M2PENT2EN';'PO3M2PENTZ13DIEN';'PO3M3CYHEXEN';'PO3M5CYPENT13DIEN';
'PO3M5FURAN23DIHY';'PO3MEFURFURAL';'PO3MGUAIACOL';'PO3MNAPT';
'PO3MPYRROLE';'PO3NAPT';'PO3OTHFURAN';'PO3OTHMONOT';
'PO3OXYFUR';'PO3OXYMCYPENONE';'PO3OXYMFUR';'PO3PENTE13DIEN';
'PO3PENTZ13DIEN';'PO3PHENOL';'PO3PYRROLE';'PO3SALAL';
'PO3SYRINGOL';'PO3TERPINOLENE';'PO3VANILIN';'PO3VGUAIACOL';
'POHAPHELLANDRENE';'POHBMYRCENE';'POHBPHELLANDRENE';
'POHC3FURANS';'POHC3PYRROLE';'POHC5H6';'POHCARENE3';
'POHCYHEX13DIEN';'POHDHYPYRROLE';'POHDIHYMFUR';'POHDIMNAP';
'POHDIMPHEN';'POHDIMPYRROLE';'POHDIMEFURAN';'POHETHFURAN2';
'POHETPYRROLE';'POHEZOCIMENE';'POHFURAN';'POHFURAN23DIHYD';
'POHFURAN25DIHYD';'POHFURFURAL';'POHFURFURAL3';'POHGUAIACOL';
'POHINDENE';'POHM1CYPENEN';'POHM1CYPENT13DIEN';'POHM2FURAN';
'POHM2OLFURAN';'POHM2PENT2EN';'POHM2PENTZ13DIEN';'POHM3CYHEXEN';
'POHM5CYPENT13DIEN';'POHM5FURAN23DIHY';'POHMEFURFURAL';
'POHMGUAIACOL';'POHMNAPT';'POHMPYRROLE';'POHNAPT';'POHOTHFURAN';
'POHOTHMONOT';'POHOXYFUR';'POHOXYMCYPENONE';'POHOXYMFUR';
'POHPENTE13DIEN';'POHPENTZ13DIEN';'POHPYRROLE';'POHSALAL';
'POHSYRINGOL';'POHTERPINOLENE';'POHVANILIN';'POHVGUAIACOL';
'PPACECN';'PPACENAP';'PPACETNH';'PPACETOL';'PPACO2H';
'PPALLYLOH';'PPANSIOL';'PPAPHELLANDRENE';'PPBENZACETCN';
'PPBENZCN';'PPBENZENE';'PPBENZHEX';'PPBENZNO2';'PPBENZPENT';
'PPBIACET';'PPBIPHENYL';'PPBMYRCENE';'PPBPHELLANDRENE';
'PPBUT2OLO';'PPBUTADIENE';'PPBUTANCN';'PPBUTE2AL';'PPBUTENAL2';
'PPBUTENCN';'PPBUTENNO3';'PPC10ARO';'PPC2H2';'PPC2H3CN';
'PPC2H5N';'PPC2H5OH';'PPC3FURANS';'PPC3MDBAL';'PPC3PYRROLE';
'PPC4H4';'PPC5H6';'PPC6CO34';'PPC6ESTERS';'PPC7ACRYCN';
'PPC7HEXENES';'PPC8HEPTENE';'PPCAMPHENE';'PPCAMPHOR';
'PPCARENE3';'PPCH3CO2H';'PPCH3COCH3';'PPCH3COCO2H';
'PPCH3NO2';'PPCH3OH';'PPCHCCOOH';'PPCINEOLE';'PPCO23C5';
'PPCO23C6';'PPCO24C6';'PPCO25C6';'PPCYHEX13DIEN';'PPCYHEXENE';
'PPCYHEXONE';'PPCYPENT2EN14DION';'PPCYPENT2EN1ON';'PPCYPENT3EN12DION';
'PPCYPENT3EN1ON';'PPCYPENTDIONE';'PPCYPENTENE';'PPCYPENTONE';
'PPDEC19DIEN';'PPDEC1EN';'PPDECANAL';'PPDHYPYRROLE';
'PPDIEK';'PPDIFURANDIONE';'PPDIHYDOXYPYR';'PPDIHYMFUR';
'PPDIHYNAP';'PPDIHYPYRD';'PPDIMDISIDE';'PPDIMNAP';'PPDIMPHEN';
'PPDIMPYRROLE';'PPDIMPYRS';'PPDM23BUT13DIEN';'PPDIMEFURAN';
'PPDM25HEX1EN';'PPDM34CYPENTEN1ONE';'PPDM35CYPENTEN';
'PPDM44CYHEPTEN';'PPDODEC111DIEN';'PPDODEC1EN';'PPE1PREK';
'PPE2PREK';'PPESTRAGOLE';'PPETCYPENTONE';'PPETENCYPENT';
'PPETH1M3BENZ';'PPETHACROL';'PPETHENCYHEX';'PPETHENNO2';
'PPETHFORM';'PPETHFURAN2';'PPETHLIINDANE';'PPETHPYRS';
'PPETHSYTRENE';'PPETPYRROLE';'PPETYNPYRROLE';'PPEVK';
'PPEZOCIMENE';'PPFURAN';'PPFURAN23DIHYD';'PPFURAN25DIHYD';
'PPFURANTETHYD';'PPFURCARBCN2';'PPFURCARBCN3';'PPFURFURAL';
'PPFURFURAL3';'PPH2S';'PPHCN';'PPHCONH2';'PPHCOOH';
'PPHEPT16DIEN';'PPHEPT3ONE';'PPHEPTCNS';'PPHEPTEN';
'PPHEX13DIEN';'PPHEX14DIEN';'PPHEX15DI3YN';'PPHEX1EN3YN';
'PPHEX2EN4YN';'PPHEX2ENE';'PPHEX2ONE';'PPHEX3ONE';'PPHEX3YN';
'PPHEXE14DIEN';'PPHEXEE24DIEN';'PPHEXEE24DIENAL';'PPHEXEX24DIEN';
'PPHNCO';'PPHONO';'PPHYBENZQUIN';'PPHYDROXCN';'PPINDANE';
'PPINDENE';'PPIPROPOL';'PPISOBUTCN';'PPISOEUGOL';'PPM1CYHEXEN';
'PPM1CYPENEN';'PPM1CYPENT13DIEN';'PPM2BK';'PPM2BUT1EN3YN';
'PPM2BUTANAL';'PPM2BUTCN';'PPM2CYPENT2EN1ON';'PPM2CYPENTON';
'PPM2FURAN';'PPM2OLFURAN';'PPM2PENT14DIEN';'PPM2PENT2EN';
'PPM2PENTE13DIEN';'PPM2PENTZ13DIEN';'PPM3BUTCN';'PPM3CO5C6';
'PPM3CYHEXEN';'PPM3CYPENT2EN1ON';'PPM3CYPENTEN';'PPM3ETH2BUT1EN';
'PPM3F';'PPM3FURAN';'PPM3PENTE2EN';'PPM3PENTZ13DIEN';
'PPM3PENTZ2EN';'PPM4CYHEX4EN';'PPM4PENT13DIEN';'PPM4PENT1EN';
'PPM5CYPENT13DIEN';'PPM5FURAN23DIHY';'PPM5PENT2EN';
'PPMACRYLATE';'PPMACRYLCN';'PPMANIMINE';'PPMANISOLE';
'PPMBENZACETO';'PPMBENZAL';'PPMCHAVICOL';'PPMCYPENTONES';
'PPMEK';'PPMEKCOH';'PPMESTPROPACD';'PPMETHACET';'PPMEFURFURAL';
'PPMIBK';'PPMIPK';'PPMMALIDE';'PPMMETACRL';'PPMNAPT';
'PPMOXYHYFUR';'PPMPENTCN';'PPMPHCOME';'PPMPRK';'PPMPROPBENZ';
'PPMPROPOATE';'PPMPYRIDINE2';'PPMPYRIDINE3';'PPMPYRROLE';
'PPMSTYRENE';'PPMTHIOL';'PPMTHIOPHENE';'PPMVK';'PPMXYLCO2H';
'PPNAPT';'PPNBUTACET';'PPNBUTOL';'PPNH3';'PPNON18DIEN';
'PPNONEN';'PPNPROACET';'PPOCT17DIEN';'PPOCTENES';'PPOTHFURAN';
'PPOTHMONOT';'PPOXYFUR';'PPOXYLCO2H';'PPOXYMCYPENONE';
'PPOXYMFUR';'PPOXYMFURONE';'PPOXYMOHFURAN';'PPOXYMONTS';
'PPOXYTETFUR';'PPPENT14DIEN';'PPPENT1EN1YN';'PPPENT1YN';
'PPPENT2ENE';'PPPENT4EN1YN';'PPPENTANCN';'PPPENTCN';
'PPPENTDENCN';'PPPENTE13DIEN';'PPPENTE2ENAL';'PPPENTE3EN1YN';
'PPPENTEN4AL';'PPPENTONE';'PPPENTZ13DIEN';'PPPENTZ3EN1YN';
'PPPHACETLY';'PPPHCOME';'PPPHEN4BUT3EN1YN';'PPPROPANCN';
'PPPROPBENZ';'PPPROPENNH3';'PPPROPYNAL';'PPPROPYNBENZ';
'PPPROPYNCN';'PPPXYLCO2H';'PPPYRAL';'PPPYRIDINE';'PPPYRIDINOL';
'PPPYRROLE';'PPSABINENE';'PPSALAL';'PPTERPINOLENE';
'PPTETMBENZ';'PPTETRADECEN';'PPTHIOPHENE';'PPTMNH3';
'PPTOLNO2';'PPTOLUENE';'PPTRIDECEN';'PPUNDEC110DIEN';
'PPUNDECEN';'PPVANILIN';'PPVFURAN';'PPVGUAIACOL';'PPVINLYLPYR';
'PROPANCN';'PROPBENZ';'PROPENNH3';'PROPYNAL';'PROPYNBENZ';
'PROPYNCN';'PXYLCO2H';'PYRAL';'PYRIDINE';'PYRIDINOL';
'PYRROLE';'SABINENE';'SALAL';'SYRINGOL';'TERPINOLENE';
'TETMBENZ';'TETRADECEN';'THIOPHENE';'TMNH3';'TOLNO2';
'TOLUENE';'TRIDECEN';'UNDEC110DIEN';'UNDECEN';'VANILIN';
'VFURAN';'VGUAIACOL';'VINLYLPYR';'DIMPHEN'};
 
RO2ToAdd = {...
 };
 
AddSpecies
 
%% Reactions list
i=i+1;
Rnames{i} = 'ACECN + NO3 = PPACECN';
k(:,i) = 5e-19;
Gstr{i,1} = 'ACECN';Gstr{i,2} = 'NO3';
fACECN(i)=fACECN(i)-1; fNO3(i)=fNO3(i)-1; fPPACECN(i)=fPPACECN(i)+1; 
 
 
i=i+1;
Rnames{i} = 'ACENAP + NO3 = PPACENAP';
k(:,i) = 5.45e-12;
Gstr{i,1} = 'ACENAP';Gstr{i,2} = 'NO3';
fACENAP(i)=fACENAP(i)-1; fNO3(i)=fNO3(i)-1; fPPACENAP(i)=fPPACENAP(i)+1; 
 
 
i=i+1;
Rnames{i} = 'ACETNH + NO3 = PPACETNH';
k(:,i) = 4.9e-14;
Gstr{i,1} = 'ACETNH';Gstr{i,2} = 'NO3';
fACETNH(i)=fACETNH(i)-1; fNO3(i)=fNO3(i)-1; fPPACETNH(i)=fPPACETNH(i)+1; 
 
 
i=i+1;
Rnames{i} = 'ACETOL + NO3 = PPACETOL';
k(:,i) = 3.16e-16;
Gstr{i,1} = 'ACETOL';Gstr{i,2} = 'NO3';
fACETOL(i)=fACETOL(i)-1; fNO3(i)=fNO3(i)-1; fPPACETOL(i)=fPPACETOL(i)+1; 
 
 
i=i+1;
Rnames{i} = 'ACO2H + NO3 = PPACO2H';
k(:,i) = 1e-17;
Gstr{i,1} = 'ACO2H';Gstr{i,2} = 'NO3';
fACO2H(i)=fACO2H(i)-1; fNO3(i)=fNO3(i)-1; fPPACO2H(i)=fPPACO2H(i)+1; 
 
 
i=i+1;
Rnames{i} = 'ALLYLOH + NO3 = PPALLYLOH';
k(:,i) = 7.7e-15;
Gstr{i,1} = 'ALLYLOH';Gstr{i,2} = 'NO3';
fALLYLOH(i)=fALLYLOH(i)-1; fNO3(i)=fNO3(i)-1; fPPALLYLOH(i)=fPPALLYLOH(i)+1; 
 
 
i=i+1;
Rnames{i} = 'ANSIOL + NO3 = PPANSIOL';
k(:,i) = 9.45e-17;
Gstr{i,1} = 'ANSIOL';Gstr{i,2} = 'NO3';
fANSIOL(i)=fANSIOL(i)-1; fNO3(i)=fNO3(i)-1; fPPANSIOL(i)=fPPANSIOL(i)+1; 
 
 
i=i+1;
Rnames{i} = 'APHELLANDRENE + NO3 = PPAPHELLANDRENE';
k(:,i) = 7.3e-11;
Gstr{i,1} = 'APHELLANDRENE';Gstr{i,2} = 'NO3';
fAPHELLANDRENE(i)=fAPHELLANDRENE(i)-1; fNO3(i)=fNO3(i)-1; fPPAPHELLANDRENE(i)=fPPAPHELLANDRENE(i)+1; 
 
 
i=i+1;
Rnames{i} = 'BENZACETCN + NO3 = PPBENZACETCN';
k(:,i) = 3e-17;
Gstr{i,1} = 'BENZACETCN';Gstr{i,2} = 'NO3';
fBENZACETCN(i)=fBENZACETCN(i)-1; fNO3(i)=fNO3(i)-1; fPPBENZACETCN(i)=fPPBENZACETCN(i)+1; 
 
 
i=i+1;
Rnames{i} = 'BENZCN + NO3 = PPBENZCN';
k(:,i) = 3e-17;
Gstr{i,1} = 'BENZCN';Gstr{i,2} = 'NO3';
fBENZCN(i)=fBENZCN(i)-1; fNO3(i)=fNO3(i)-1; fPPBENZCN(i)=fPPBENZCN(i)+1; 
 
 
i=i+1;
Rnames{i} = 'BENZENE + NO3 = PPBENZENE';
k(:,i) = 3e-17;
Gstr{i,1} = 'BENZENE';Gstr{i,2} = 'NO3';
fBENZENE(i)=fBENZENE(i)-1; fNO3(i)=fNO3(i)-1; fPPBENZENE(i)=fPPBENZENE(i)+1; 
 
 
i=i+1;
Rnames{i} = 'BENZHEX + NO3 = PPBENZHEX';
k(:,i) = 1.4e-16;
Gstr{i,1} = 'BENZHEX';Gstr{i,2} = 'NO3';
fBENZHEX(i)=fBENZHEX(i)-1; fNO3(i)=fNO3(i)-1; fPPBENZHEX(i)=fPPBENZHEX(i)+1; 
 
 
i=i+1;
Rnames{i} = 'BENZNO2 + NO3 = PPBENZNO2';
k(:,i) = 3e-17;
Gstr{i,1} = 'BENZNO2';Gstr{i,2} = 'NO3';
fBENZNO2(i)=fBENZNO2(i)-1; fNO3(i)=fNO3(i)-1; fPPBENZNO2(i)=fPPBENZNO2(i)+1; 
 
 
i=i+1;
Rnames{i} = 'BENZPENT + NO3 = PPBENZPENT';
k(:,i) = 1.4e-16;
Gstr{i,1} = 'BENZPENT';Gstr{i,2} = 'NO3';
fBENZPENT(i)=fBENZPENT(i)-1; fNO3(i)=fNO3(i)-1; fPPBENZPENT(i)=fPPBENZPENT(i)+1; 
 
 
i=i+1;
Rnames{i} = 'BIACET + NO3 = PPBIACET';
k(:,i) = 1.28e-18;
Gstr{i,1} = 'BIACET';Gstr{i,2} = 'NO3';
fBIACET(i)=fBIACET(i)-1; fNO3(i)=fNO3(i)-1; fPPBIACET(i)=fPPBIACET(i)+1; 
 
 
i=i+1;
Rnames{i} = 'BIPHENYL + NO3 = PPBIPHENYL';
k(:,i) = 3e-17;
Gstr{i,1} = 'BIPHENYL';Gstr{i,2} = 'NO3';
fBIPHENYL(i)=fBIPHENYL(i)-1; fNO3(i)=fNO3(i)-1; fPPBIPHENYL(i)=fPPBIPHENYL(i)+1; 
 
 
i=i+1;
Rnames{i} = 'BMYRCENE + NO3 = PPBMYRCENE';
k(:,i) = 1.1e-11;
Gstr{i,1} = 'BMYRCENE';Gstr{i,2} = 'NO3';
fBMYRCENE(i)=fBMYRCENE(i)-1; fNO3(i)=fNO3(i)-1; fPPBMYRCENE(i)=fPPBMYRCENE(i)+1; 
 
 
i=i+1;
Rnames{i} = 'BPHELLANDRENE + NO3 = PPBPHELLANDRENE';
k(:,i) = 7.97e-12;
Gstr{i,1} = 'BPHELLANDRENE';Gstr{i,2} = 'NO3';
fBPHELLANDRENE(i)=fBPHELLANDRENE(i)-1; fNO3(i)=fNO3(i)-1; fPPBPHELLANDRENE(i)=fPPBPHELLANDRENE(i)+1; 
 
 
i=i+1;
Rnames{i} = 'BUT2OLO + NO3 = PPBUT2OLO';
k(:,i) = 6.5e-16;
Gstr{i,1} = 'BUT2OLO';Gstr{i,2} = 'NO3';
fBUT2OLO(i)=fBUT2OLO(i)-1; fNO3(i)=fNO3(i)-1; fPPBUT2OLO(i)=fPPBUT2OLO(i)+1; 
 
 
i=i+1;
Rnames{i} = 'BUTADIENE + NO3 = PPBUTADIENE';
k(:,i) = 1e-13;
Gstr{i,1} = 'BUTADIENE';Gstr{i,2} = 'NO3';
fBUTADIENE(i)=fBUTADIENE(i)-1; fNO3(i)=fNO3(i)-1; fPPBUTADIENE(i)=fPPBUTADIENE(i)+1; 
 
 
i=i+1;
Rnames{i} = 'BUTANCN + NO3 = PPBUTANCN';
k(:,i) = 1e-18;
Gstr{i,1} = 'BUTANCN';Gstr{i,2} = 'NO3';
fBUTANCN(i)=fBUTANCN(i)-1; fNO3(i)=fNO3(i)-1; fPPBUTANCN(i)=fPPBUTANCN(i)+1; 
 
 
i=i+1;
Rnames{i} = 'BUTE2AL + NO3 = PPBUTE2AL';
k(:,i) = 5.11e-15;
Gstr{i,1} = 'BUTE2AL';Gstr{i,2} = 'NO3';
fBUTE2AL(i)=fBUTE2AL(i)-1; fNO3(i)=fNO3(i)-1; fPPBUTE2AL(i)=fPPBUTE2AL(i)+1; 
 
 
i=i+1;
Rnames{i} = 'BUTENAL2 + NO3 = PPBUTENAL2';
k(:,i) = 5.11e-15;
Gstr{i,1} = 'BUTENAL2';Gstr{i,2} = 'NO3';
fBUTENAL2(i)=fBUTENAL2(i)-1; fNO3(i)=fNO3(i)-1; fPPBUTENAL2(i)=fPPBUTENAL2(i)+1; 
 
 
i=i+1;
Rnames{i} = 'BUTENCN + NO3 = PPBUTENCN';
k(:,i) = 1.25e-14;
Gstr{i,1} = 'BUTENCN';Gstr{i,2} = 'NO3';
fBUTENCN(i)=fBUTENCN(i)-1; fNO3(i)=fNO3(i)-1; fPPBUTENCN(i)=fPPBUTENCN(i)+1; 
 
 
i=i+1;
Rnames{i} = 'BUTENNO3 + NO3 = PPBUTENNO3';
k(:,i) = 1.32e-14;
Gstr{i,1} = 'BUTENNO3';Gstr{i,2} = 'NO3';
fBUTENNO3(i)=fBUTENNO3(i)-1; fNO3(i)=fNO3(i)-1; fPPBUTENNO3(i)=fPPBUTENNO3(i)+1; 
 
 
i=i+1;
Rnames{i} = 'C10ARO + NO3 = PPC10ARO';
k(:,i) = 1e-15;
Gstr{i,1} = 'C10ARO';Gstr{i,2} = 'NO3';
fC10ARO(i)=fC10ARO(i)-1; fNO3(i)=fNO3(i)-1; fPPC10ARO(i)=fPPC10ARO(i)+1; 
 
 
i=i+1;
Rnames{i} = 'C2H2 + NO3 = PPC2H2';
k(:,i) = 1e-16;
Gstr{i,1} = 'C2H2';Gstr{i,2} = 'NO3';
fC2H2(i)=fC2H2(i)-1; fNO3(i)=fNO3(i)-1; fPPC2H2(i)=fPPC2H2(i)+1; 
 
 
i=i+1;
Rnames{i} = 'C2H3CN + NO3 = PPC2H3CN';
k(:,i) = 5.15e-13;
Gstr{i,1} = 'C2H3CN';Gstr{i,2} = 'NO3';
fC2H3CN(i)=fC2H3CN(i)-1; fNO3(i)=fNO3(i)-1; fPPC2H3CN(i)=fPPC2H3CN(i)+1; 
 
 
i=i+1;
Rnames{i} = 'C2H5N + NO3 = PPC2H5N';
k(:,i) = 1.1e-12;
Gstr{i,1} = 'C2H5N';Gstr{i,2} = 'NO3';
fC2H5N(i)=fC2H5N(i)-1; fNO3(i)=fNO3(i)-1; fPPC2H5N(i)=fPPC2H5N(i)+1; 
 
 
i=i+1;
Rnames{i} = 'C2H5OH + NO3 = PPC2H5OH';
k(:,i) = 2e-15;
Gstr{i,1} = 'C2H5OH';Gstr{i,2} = 'NO3';
fC2H5OH(i)=fC2H5OH(i)-1; fNO3(i)=fNO3(i)-1; fPPC2H5OH(i)=fPPC2H5OH(i)+1; 
 
 
i=i+1;
Rnames{i} = 'C3FURANS + NO3 = PPC3FURANS';
k(:,i) = 5.78e-11;
Gstr{i,1} = 'C3FURANS';Gstr{i,2} = 'NO3';
fC3FURANS(i)=fC3FURANS(i)-1; fNO3(i)=fNO3(i)-1; fPPC3FURANS(i)=fPPC3FURANS(i)+1; 
 
 
i=i+1;
Rnames{i} = 'C3MDBAL + NO3 = PPC3MDBAL';
k(:,i) = 3e-14;
Gstr{i,1} = 'C3MDBAL';Gstr{i,2} = 'NO3';
fC3MDBAL(i)=fC3MDBAL(i)-1; fNO3(i)=fNO3(i)-1; fPPC3MDBAL(i)=fPPC3MDBAL(i)+1; 
 
 
i=i+1;
Rnames{i} = 'C3PYRROLE + NO3 = PPC3PYRROLE';
k(:,i) = 4.6e-11;
Gstr{i,1} = 'C3PYRROLE';Gstr{i,2} = 'NO3';
fC3PYRROLE(i)=fC3PYRROLE(i)-1; fNO3(i)=fNO3(i)-1; fPPC3PYRROLE(i)=fPPC3PYRROLE(i)+1; 
 
 
i=i+1;
Rnames{i} = 'C4H4 + NO3 = PPC4H4';
k(:,i) = 1.25e-14;
Gstr{i,1} = 'C4H4';Gstr{i,2} = 'NO3';
fC4H4(i)=fC4H4(i)-1; fNO3(i)=fNO3(i)-1; fPPC4H4(i)=fPPC4H4(i)+1; 
 
 
i=i+1;
Rnames{i} = 'C5H6 + NO3 = PPC5H6';
k(:,i) = 2.34e-12;
Gstr{i,1} = 'C5H6';Gstr{i,2} = 'NO3';
fC5H6(i)=fC5H6(i)-1; fNO3(i)=fNO3(i)-1; fPPC5H6(i)=fPPC5H6(i)+1; 
 
 
i=i+1;
Rnames{i} = 'C6CO34 + NO3 = PPC6CO34';
k(:,i) = 7.3e-15;
Gstr{i,1} = 'C6CO34';Gstr{i,2} = 'NO3';
fC6CO34(i)=fC6CO34(i)-1; fNO3(i)=fNO3(i)-1; fPPC6CO34(i)=fPPC6CO34(i)+1; 
 
 
i=i+1;
Rnames{i} = 'C6ESTERS + NO3 = PPC6ESTERS';
k(:,i) = 2.27e-14;
Gstr{i,1} = 'C6ESTERS';Gstr{i,2} = 'NO3';
fC6ESTERS(i)=fC6ESTERS(i)-1; fNO3(i)=fNO3(i)-1; fPPC6ESTERS(i)=fPPC6ESTERS(i)+1; 
 
 
i=i+1;
Rnames{i} = 'C7ACRYCN + NO3 = PPC7ACRYCN';
k(:,i) = 5.15e-13;
Gstr{i,1} = 'C7ACRYCN';Gstr{i,2} = 'NO3';
fC7ACRYCN(i)=fC7ACRYCN(i)-1; fNO3(i)=fNO3(i)-1; fPPC7ACRYCN(i)=fPPC7ACRYCN(i)+1; 
 
 
i=i+1;
Rnames{i} = 'C7HEXENES + NO3 = PPC7HEXENES';
k(:,i) = 4.9e-13;
Gstr{i,1} = 'C7HEXENES';Gstr{i,2} = 'NO3';
fC7HEXENES(i)=fC7HEXENES(i)-1; fNO3(i)=fNO3(i)-1; fPPC7HEXENES(i)=fPPC7HEXENES(i)+1; 
 
 
i=i+1;
Rnames{i} = 'C8HEPTENE + NO3 = PPC8HEPTENE';
k(:,i) = 4.36e-13;
Gstr{i,1} = 'C8HEPTENE';Gstr{i,2} = 'NO3';
fC8HEPTENE(i)=fC8HEPTENE(i)-1; fNO3(i)=fNO3(i)-1; fPPC8HEPTENE(i)=fPPC8HEPTENE(i)+1; 
 
 
i=i+1;
Rnames{i} = 'CAMPHENE + NO3 = PPCAMPHENE';
k(:,i) = 6.6e-13;
Gstr{i,1} = 'CAMPHENE';Gstr{i,2} = 'NO3';
fCAMPHENE(i)=fCAMPHENE(i)-1; fNO3(i)=fNO3(i)-1; fPPCAMPHENE(i)=fPPCAMPHENE(i)+1; 
 
 
i=i+1;
Rnames{i} = 'CAMPHOR + NO3 = PPCAMPHOR';
k(:,i) = 3e-16;
Gstr{i,1} = 'CAMPHOR';Gstr{i,2} = 'NO3';
fCAMPHOR(i)=fCAMPHOR(i)-1; fNO3(i)=fNO3(i)-1; fPPCAMPHOR(i)=fPPCAMPHOR(i)+1; 
 
 
i=i+1;
Rnames{i} = 'CARENE3 + NO3 = PPCARENE3';
k(:,i) = 9.1e-12;
Gstr{i,1} = 'CARENE3';Gstr{i,2} = 'NO3';
fCARENE3(i)=fCARENE3(i)-1; fNO3(i)=fNO3(i)-1; fPPCARENE3(i)=fPPCARENE3(i)+1; 
 
 
i=i+1;
Rnames{i} = 'CH3CO2H + NO3 = PPCH3CO2H';
k(:,i) = 1e-17;
Gstr{i,1} = 'CH3CO2H';Gstr{i,2} = 'NO3';
fCH3CO2H(i)=fCH3CO2H(i)-1; fNO3(i)=fNO3(i)-1; fPPCH3CO2H(i)=fPPCH3CO2H(i)+1; 
 
 
i=i+1;
Rnames{i} = 'CH3COCH3 + NO3 = PPCH3COCH3';
k(:,i) = 3e-17;
Gstr{i,1} = 'CH3COCH3';Gstr{i,2} = 'NO3';
fCH3COCH3(i)=fCH3COCH3(i)-1; fNO3(i)=fNO3(i)-1; fPPCH3COCH3(i)=fPPCH3COCH3(i)+1; 
 
 
i=i+1;
Rnames{i} = 'CH3COCO2H + NO3 = PPCH3COCO2H';
k(:,i) = 1e-17;
Gstr{i,1} = 'CH3COCO2H';Gstr{i,2} = 'NO3';
fCH3COCO2H(i)=fCH3COCO2H(i)-1; fNO3(i)=fNO3(i)-1; fPPCH3COCO2H(i)=fPPCH3COCO2H(i)+1; 
 
 
i=i+1;
Rnames{i} = 'CH3NO2 + NO3 = PPCH3NO2';
k(:,i) = 1e-18;
Gstr{i,1} = 'CH3NO2';Gstr{i,2} = 'NO3';
fCH3NO2(i)=fCH3NO2(i)-1; fNO3(i)=fNO3(i)-1; fPPCH3NO2(i)=fPPCH3NO2(i)+1; 
 
 
i=i+1;
Rnames{i} = 'CH3OH + NO3 = PPCH3OH';
k(:,i) = 2.4e-16;
Gstr{i,1} = 'CH3OH';Gstr{i,2} = 'NO3';
fCH3OH(i)=fCH3OH(i)-1; fNO3(i)=fNO3(i)-1; fPPCH3OH(i)=fPPCH3OH(i)+1; 
 
 
i=i+1;
Rnames{i} = 'CHCCOOH + NO3 = PPCHCCOOH';
k(:,i) = 1e-17;
Gstr{i,1} = 'CHCCOOH';Gstr{i,2} = 'NO3';
fCHCCOOH(i)=fCHCCOOH(i)-1; fNO3(i)=fNO3(i)-1; fPPCHCCOOH(i)=fPPCHCCOOH(i)+1; 
 
 
i=i+1;
Rnames{i} = 'CINEOLE + NO3 = PPCINEOLE';
k(:,i) = 1.69e-16;
Gstr{i,1} = 'CINEOLE';Gstr{i,2} = 'NO3';
fCINEOLE(i)=fCINEOLE(i)-1; fNO3(i)=fNO3(i)-1; fPPCINEOLE(i)=fPPCINEOLE(i)+1; 
 
 
i=i+1;
Rnames{i} = 'CO23C5 + NO3 = PPCO23C5';
k(:,i) = 1e-15;
Gstr{i,1} = 'CO23C5';Gstr{i,2} = 'NO3';
fCO23C5(i)=fCO23C5(i)-1; fNO3(i)=fNO3(i)-1; fPPCO23C5(i)=fPPCO23C5(i)+1; 
 
 
i=i+1;
Rnames{i} = 'CO23C6 + NO3 = PPCO23C6';
k(:,i) = 7.3e-15;
Gstr{i,1} = 'CO23C6';Gstr{i,2} = 'NO3';
fCO23C6(i)=fCO23C6(i)-1; fNO3(i)=fNO3(i)-1; fPPCO23C6(i)=fPPCO23C6(i)+1; 
 
 
i=i+1;
Rnames{i} = 'CO24C6 + NO3 = PPCO24C6';
k(:,i) = 7.3e-15;
Gstr{i,1} = 'CO24C6';Gstr{i,2} = 'NO3';
fCO24C6(i)=fCO24C6(i)-1; fNO3(i)=fNO3(i)-1; fPPCO24C6(i)=fPPCO24C6(i)+1; 
 
 
i=i+1;
Rnames{i} = 'CO25C6 + NO3 = PPCO25C6';
k(:,i) = 7.3e-15;
Gstr{i,1} = 'CO25C6';Gstr{i,2} = 'NO3';
fCO25C6(i)=fCO25C6(i)-1; fNO3(i)=fNO3(i)-1; fPPCO25C6(i)=fPPCO25C6(i)+1; 
 
 
i=i+1;
Rnames{i} = 'CYHEX13DIEN + NO3 = PPCYHEX13DIEN';
k(:,i) = 1.08e-11;
Gstr{i,1} = 'CYHEX13DIEN';Gstr{i,2} = 'NO3';
fCYHEX13DIEN(i)=fCYHEX13DIEN(i)-1; fNO3(i)=fNO3(i)-1; fPPCYHEX13DIEN(i)=fPPCYHEX13DIEN(i)+1; 
 
 
i=i+1;
Rnames{i} = 'CYHEXENE + NO3 = PPCYHEXENE';
k(:,i) = 5.4e-13;
Gstr{i,1} = 'CYHEXENE';Gstr{i,2} = 'NO3';
fCYHEXENE(i)=fCYHEXENE(i)-1; fNO3(i)=fNO3(i)-1; fPPCYHEXENE(i)=fPPCYHEXENE(i)+1; 
 
 
i=i+1;
Rnames{i} = 'CYHEXONE + NO3 = PPCYHEXONE';
k(:,i) = 1e-15;
Gstr{i,1} = 'CYHEXONE';Gstr{i,2} = 'NO3';
fCYHEXONE(i)=fCYHEXONE(i)-1; fNO3(i)=fNO3(i)-1; fPPCYHEXONE(i)=fPPCYHEXONE(i)+1; 
 
 
i=i+1;
Rnames{i} = 'CYPENT2EN14DION + NO3 = PPCYPENT2EN14DION';
k(:,i) = 1.46e-16;
Gstr{i,1} = 'CYPENT2EN14DION';Gstr{i,2} = 'NO3';
fCYPENT2EN14DION(i)=fCYPENT2EN14DION(i)-1; fNO3(i)=fNO3(i)-1; fPPCYPENT2EN14DION(i)=fPPCYPENT2EN14DION(i)+1; 
 
 
i=i+1;
Rnames{i} = 'CYPENT2EN1ON + NO3 = PPCYPENT2EN1ON';
k(:,i) = 7.86e-15;
Gstr{i,1} = 'CYPENT2EN1ON';Gstr{i,2} = 'NO3';
fCYPENT2EN1ON(i)=fCYPENT2EN1ON(i)-1; fNO3(i)=fNO3(i)-1; fPPCYPENT2EN1ON(i)=fPPCYPENT2EN1ON(i)+1; 
 
 
i=i+1;
Rnames{i} = 'CYPENT3EN12DION + NO3 = PPCYPENT3EN12DION';
k(:,i) = 7.84e-15;
Gstr{i,1} = 'CYPENT3EN12DION';Gstr{i,2} = 'NO3';
fCYPENT3EN12DION(i)=fCYPENT3EN12DION(i)-1; fNO3(i)=fNO3(i)-1; fPPCYPENT3EN12DION(i)=fPPCYPENT3EN12DION(i)+1; 
 
 
i=i+1;
Rnames{i} = 'CYPENT3EN1ON + NO3 = PPCYPENT3EN1ON';
k(:,i) = 1.49e-13;
Gstr{i,1} = 'CYPENT3EN1ON';Gstr{i,2} = 'NO3';
fCYPENT3EN1ON(i)=fCYPENT3EN1ON(i)-1; fNO3(i)=fNO3(i)-1; fPPCYPENT3EN1ON(i)=fPPCYPENT3EN1ON(i)+1; 
 
 
i=i+1;
Rnames{i} = 'CYPENTDIONE + NO3 = PPCYPENTDIONE';
k(:,i) = 1.63e-13;
Gstr{i,1} = 'CYPENTDIONE';Gstr{i,2} = 'NO3';
fCYPENTDIONE(i)=fCYPENTDIONE(i)-1; fNO3(i)=fNO3(i)-1; fPPCYPENTDIONE(i)=fPPCYPENTDIONE(i)+1; 
 
 
i=i+1;
Rnames{i} = 'CYPENTENE + NO3 = PPCYPENTENE';
k(:,i) = 7e-13;
Gstr{i,1} = 'CYPENTENE';Gstr{i,2} = 'NO3';
fCYPENTENE(i)=fCYPENTENE(i)-1; fNO3(i)=fNO3(i)-1; fPPCYPENTENE(i)=fPPCYPENTENE(i)+1; 
 
 
i=i+1;
Rnames{i} = 'CYPENTONE + NO3 = PPCYPENTONE';
k(:,i) = 8.27e-15;
Gstr{i,1} = 'CYPENTONE';Gstr{i,2} = 'NO3';
fCYPENTONE(i)=fCYPENTONE(i)-1; fNO3(i)=fNO3(i)-1; fPPCYPENTONE(i)=fPPCYPENTONE(i)+1; 
 
 
i=i+1;
Rnames{i} = 'DEC19DIEN + NO3 = PPDEC19DIEN';
k(:,i) = 3.13e-14;
Gstr{i,1} = 'DEC19DIEN';Gstr{i,2} = 'NO3';
fDEC19DIEN(i)=fDEC19DIEN(i)-1; fNO3(i)=fNO3(i)-1; fPPDEC19DIEN(i)=fPPDEC19DIEN(i)+1; 
 
 
i=i+1;
Rnames{i} = 'DEC1EN + NO3 = PPDEC1EN';
k(:,i) = 2.55e-14;
Gstr{i,1} = 'DEC1EN';Gstr{i,2} = 'NO3';
fDEC1EN(i)=fDEC1EN(i)-1; fNO3(i)=fNO3(i)-1; fPPDEC1EN(i)=fPPDEC1EN(i)+1; 
 
 
i=i+1;
Rnames{i} = 'DECANAL + NO3 = PPDECANAL';
k(:,i) = 2.2e-14;
Gstr{i,1} = 'DECANAL';Gstr{i,2} = 'NO3';
fDECANAL(i)=fDECANAL(i)-1; fNO3(i)=fNO3(i)-1; fPPDECANAL(i)=fPPDECANAL(i)+1; 
 
 
i=i+1;
Rnames{i} = 'DHYPYRROLE + NO3 = PPDHYPYRROLE';
k(:,i) = 4.6e-11;
Gstr{i,1} = 'DHYPYRROLE';Gstr{i,2} = 'NO3';
fDHYPYRROLE(i)=fDHYPYRROLE(i)-1; fNO3(i)=fNO3(i)-1; fPPDHYPYRROLE(i)=fPPDHYPYRROLE(i)+1; 
 
 
i=i+1;
Rnames{i} = 'DIEK + NO3 = PPDIEK';
k(:,i) = 1e-15;
Gstr{i,1} = 'DIEK';Gstr{i,2} = 'NO3';
fDIEK(i)=fDIEK(i)-1; fNO3(i)=fNO3(i)-1; fPPDIEK(i)=fPPDIEK(i)+1; 
 
 
i=i+1;
Rnames{i} = 'DIFURANDIONE + NO3 = PPDIFURANDIONE';
k(:,i) = 3.3e-17;
Gstr{i,1} = 'DIFURANDIONE';Gstr{i,2} = 'NO3';
fDIFURANDIONE(i)=fDIFURANDIONE(i)-1; fNO3(i)=fNO3(i)-1; fPPDIFURANDIONE(i)=fPPDIFURANDIONE(i)+1; 
 
 
i=i+1;
Rnames{i} = 'DIHYDOXYPYR + NO3 = PPDIHYDOXYPYR';
k(:,i) = 2e-13;
Gstr{i,1} = 'DIHYDOXYPYR';Gstr{i,2} = 'NO3';
fDIHYDOXYPYR(i)=fDIHYDOXYPYR(i)-1; fNO3(i)=fNO3(i)-1; fPPDIHYDOXYPYR(i)=fPPDIHYDOXYPYR(i)+1; 
 
 
i=i+1;
Rnames{i} = 'DIHYMFUR + NO3 = PPDIHYMFUR';
k(:,i) = 5.78e-11;
Gstr{i,1} = 'DIHYMFUR';Gstr{i,2} = 'NO3';
fDIHYMFUR(i)=fDIHYMFUR(i)-1; fNO3(i)=fNO3(i)-1; fPPDIHYMFUR(i)=fPPDIHYMFUR(i)+1; 
 
 
i=i+1;
Rnames{i} = 'DIHYNAP + NO3 = PPDIHYNAP';
k(:,i) = 8.6e-15;
Gstr{i,1} = 'DIHYNAP';Gstr{i,2} = 'NO3';
fDIHYNAP(i)=fDIHYNAP(i)-1; fNO3(i)=fNO3(i)-1; fPPDIHYNAP(i)=fPPDIHYNAP(i)+1; 
 
 
i=i+1;
Rnames{i} = 'DIHYPYRD + NO3 = PPDIHYPYRD';
k(:,i) = 4.8e-13;
Gstr{i,1} = 'DIHYPYRD';Gstr{i,2} = 'NO3';
fDIHYPYRD(i)=fDIHYPYRD(i)-1; fNO3(i)=fNO3(i)-1; fPPDIHYPYRD(i)=fPPDIHYPYRD(i)+1; 
 
 
i=i+1;
Rnames{i} = 'DIMDISIDE + NO3 = PPDIMDISIDE';
k(:,i) = 7e-13;
Gstr{i,1} = 'DIMDISIDE';Gstr{i,2} = 'NO3';
fDIMDISIDE(i)=fDIMDISIDE(i)-1; fNO3(i)=fNO3(i)-1; fPPDIMDISIDE(i)=fPPDIMDISIDE(i)+1; 
 
 
i=i+1;
Rnames{i} = 'DIMNAP + NO3 = PPDIMNAP';
k(:,i) = 2e-11;
Gstr{i,1} = 'DIMNAP';Gstr{i,2} = 'NO3';
fDIMNAP(i)=fDIMNAP(i)-1; fNO3(i)=fNO3(i)-1; fPPDIMNAP(i)=fPPDIMNAP(i)+1; 
 
 
i=i+1;
Rnames{i} = 'DIMPHEN + NO3 = PPDIMPHEN';
k(:,i) = 2.91e-11;
Gstr{i,1} = 'DIMPHEN';Gstr{i,2} = 'NO3';
fDIMPHEN(i)=fDIMPHEN(i)-1; fNO3(i)=fNO3(i)-1; fPPDIMPHEN(i)=fPPDIMPHEN(i)+1; 
 
 
i=i+1;
Rnames{i} = 'DIMPYRROLE + NO3 = PPDIMPYRROLE';
k(:,i) = 4.6e-11;
Gstr{i,1} = 'DIMPYRROLE';Gstr{i,2} = 'NO3';
fDIMPYRROLE(i)=fDIMPYRROLE(i)-1; fNO3(i)=fNO3(i)-1; fPPDIMPYRROLE(i)=fPPDIMPYRROLE(i)+1; 
 
 
i=i+1;
Rnames{i} = 'DIMPYRS + NO3 = PPDIMPYRS';
k(:,i) = 4.8e-13;
Gstr{i,1} = 'DIMPYRS';Gstr{i,2} = 'NO3';
fDIMPYRS(i)=fDIMPYRS(i)-1; fNO3(i)=fNO3(i)-1; fPPDIMPYRS(i)=fPPDIMPYRS(i)+1; 
 
 
i=i+1;
Rnames{i} = 'DM23BUT13DIEN + NO3 = PPDM23BUT13DIEN';
k(:,i) = 1.37e-12;
Gstr{i,1} = 'DM23BUT13DIEN';Gstr{i,2} = 'NO3';
fDM23BUT13DIEN(i)=fDM23BUT13DIEN(i)-1; fNO3(i)=fNO3(i)-1; fPPDM23BUT13DIEN(i)=fPPDM23BUT13DIEN(i)+1; 
 
 
i=i+1;
Rnames{i} = 'DIMEFURAN + NO3 = PPDIMEFURAN';
k(:,i) = 5.78e-11;
Gstr{i,1} = 'DIMEFURAN';Gstr{i,2} = 'NO3';
fDIMEFURAN(i)=fDIMEFURAN(i)-1; fNO3(i)=fNO3(i)-1; fPPDIMEFURAN(i)=fPPDIMEFURAN(i)+1; 
 
 
i=i+1;
Rnames{i} = 'DM25HEX1EN + NO3 = PPDM25HEX1EN';
k(:,i) = 3.91e-13;
Gstr{i,1} = 'DM25HEX1EN';Gstr{i,2} = 'NO3';
fDM25HEX1EN(i)=fDM25HEX1EN(i)-1; fNO3(i)=fNO3(i)-1; fPPDM25HEX1EN(i)=fPPDM25HEX1EN(i)+1; 
 
 
i=i+1;
Rnames{i} = 'DM34CYPENTEN1ONE + NO3 = PPDM34CYPENTEN1ONE';
k(:,i) = 1.62e-13;
Gstr{i,1} = 'DM34CYPENTEN1ONE';Gstr{i,2} = 'NO3';
fDM34CYPENTEN1ONE(i)=fDM34CYPENTEN1ONE(i)-1; fNO3(i)=fNO3(i)-1; fPPDM34CYPENTEN1ONE(i)=fPPDM34CYPENTEN1ONE(i)+1; 
 
 
i=i+1;
Rnames{i} = 'DM35CYPENTEN + NO3 = PPDM35CYPENTEN';
k(:,i) = 3.2e-13;
Gstr{i,1} = 'DM35CYPENTEN';Gstr{i,2} = 'NO3';
fDM35CYPENTEN(i)=fDM35CYPENTEN(i)-1; fNO3(i)=fNO3(i)-1; fPPDM35CYPENTEN(i)=fPPDM35CYPENTEN(i)+1; 
 
 
i=i+1;
Rnames{i} = 'DM44CYHEPTEN + NO3 = PPDM44CYHEPTEN';
k(:,i) = 4.5e-13;
Gstr{i,1} = 'DM44CYHEPTEN';Gstr{i,2} = 'NO3';
fDM44CYHEPTEN(i)=fDM44CYHEPTEN(i)-1; fNO3(i)=fNO3(i)-1; fPPDM44CYHEPTEN(i)=fPPDM44CYHEPTEN(i)+1; 
 
 
i=i+1;
Rnames{i} = 'DODEC111DIEN + NO3 = PPDODEC111DIEN';
k(:,i) = 3.88e-14;
Gstr{i,1} = 'DODEC111DIEN';Gstr{i,2} = 'NO3';
fDODEC111DIEN(i)=fDODEC111DIEN(i)-1; fNO3(i)=fNO3(i)-1; fPPDODEC111DIEN(i)=fPPDODEC111DIEN(i)+1; 
 
 
i=i+1;
Rnames{i} = 'DODEC1EN + NO3 = PPDODEC1EN';
k(:,i) = 2.22e-14;
Gstr{i,1} = 'DODEC1EN';Gstr{i,2} = 'NO3';
fDODEC1EN(i)=fDODEC1EN(i)-1; fNO3(i)=fNO3(i)-1; fPPDODEC1EN(i)=fPPDODEC1EN(i)+1; 
 
 
i=i+1;
Rnames{i} = 'E1PREK + NO3 = PPE1PREK';
k(:,i) = 7.77e-14;
Gstr{i,1} = 'E1PREK';Gstr{i,2} = 'NO3';
fE1PREK(i)=fE1PREK(i)-1; fNO3(i)=fNO3(i)-1; fPPE1PREK(i)=fPPE1PREK(i)+1; 
 
 
i=i+1;
Rnames{i} = 'E2PREK + NO3 = PPE2PREK';
k(:,i) = 7.77e-14;
Gstr{i,1} = 'E2PREK';Gstr{i,2} = 'NO3';
fE2PREK(i)=fE2PREK(i)-1; fNO3(i)=fNO3(i)-1; fPPE2PREK(i)=fPPE2PREK(i)+1; 
 
 
i=i+1;
Rnames{i} = 'ESTRAGOLE + NO3 = PPESTRAGOLE';
k(:,i) = 1.6e-13;
Gstr{i,1} = 'ESTRAGOLE';Gstr{i,2} = 'NO3';
fESTRAGOLE(i)=fESTRAGOLE(i)-1; fNO3(i)=fNO3(i)-1; fPPESTRAGOLE(i)=fPPESTRAGOLE(i)+1; 
 
 
i=i+1;
Rnames{i} = 'ETCYPENTONE + NO3 = PPETCYPENTONE';
k(:,i) = 1.55e-16;
Gstr{i,1} = 'ETCYPENTONE';Gstr{i,2} = 'NO3';
fETCYPENTONE(i)=fETCYPENTONE(i)-1; fNO3(i)=fNO3(i)-1; fPPETCYPENTONE(i)=fPPETCYPENTONE(i)+1; 
 
 
i=i+1;
Rnames{i} = 'ETENCYPENT + NO3 = PPETENCYPENT';
k(:,i) = 1.1e-11;
Gstr{i,1} = 'ETENCYPENT';Gstr{i,2} = 'NO3';
fETENCYPENT(i)=fETENCYPENT(i)-1; fNO3(i)=fNO3(i)-1; fPPETENCYPENT(i)=fPPETENCYPENT(i)+1; 
 
 
i=i+1;
Rnames{i} = 'ETH1M3BENZ + NO3 = PPETH1M3BENZ';
k(:,i) = 5.71e-16;
Gstr{i,1} = 'ETH1M3BENZ';Gstr{i,2} = 'NO3';
fETH1M3BENZ(i)=fETH1M3BENZ(i)-1; fNO3(i)=fNO3(i)-1; fPPETH1M3BENZ(i)=fPPETH1M3BENZ(i)+1; 
 
 
i=i+1;
Rnames{i} = 'ETHACROL + NO3 = PPETHACROL';
k(:,i) = 2.14e-14;
Gstr{i,1} = 'ETHACROL';Gstr{i,2} = 'NO3';
fETHACROL(i)=fETHACROL(i)-1; fNO3(i)=fNO3(i)-1; fPPETHACROL(i)=fPPETHACROL(i)+1; 
 
 
i=i+1;
Rnames{i} = 'ETHENCYHEX + NO3 = PPETHENCYHEX';
k(:,i) = 4.3e-12;
Gstr{i,1} = 'ETHENCYHEX';Gstr{i,2} = 'NO3';
fETHENCYHEX(i)=fETHENCYHEX(i)-1; fNO3(i)=fNO3(i)-1; fPPETHENCYHEX(i)=fPPETHENCYHEX(i)+1; 
 
 
i=i+1;
Rnames{i} = 'ETHENNO2 + NO3 = PPETHENNO2';
k(:,i) = 2.1e-16;
Gstr{i,1} = 'ETHENNO2';Gstr{i,2} = 'NO3';
fETHENNO2(i)=fETHENNO2(i)-1; fNO3(i)=fNO3(i)-1; fPPETHENNO2(i)=fPPETHENNO2(i)+1; 
 
 
i=i+1;
Rnames{i} = 'ETHFORM + NO3 = PPETHFORM';
k(:,i) = 1.69e-17;
Gstr{i,1} = 'ETHFORM';Gstr{i,2} = 'NO3';
fETHFORM(i)=fETHFORM(i)-1; fNO3(i)=fNO3(i)-1; fPPETHFORM(i)=fPPETHFORM(i)+1; 
 
 
i=i+1;
Rnames{i} = 'ETHFURAN2 + NO3 = PPETHFURAN2';
k(:,i) = 1.3e-11;
Gstr{i,1} = 'ETHFURAN2';Gstr{i,2} = 'NO3';
fETHFURAN2(i)=fETHFURAN2(i)-1; fNO3(i)=fNO3(i)-1; fPPETHFURAN2(i)=fPPETHFURAN2(i)+1; 
 
 
i=i+1;
Rnames{i} = 'ETHLIINDANE + NO3 = PPETHLIINDANE';
k(:,i) = 4.1e-12;
Gstr{i,1} = 'ETHLIINDANE';Gstr{i,2} = 'NO3';
fETHLIINDANE(i)=fETHLIINDANE(i)-1; fNO3(i)=fNO3(i)-1; fPPETHLIINDANE(i)=fPPETHLIINDANE(i)+1; 
 
 
i=i+1;
Rnames{i} = 'ETHPYRS + NO3 = PPETHPYRS';
k(:,i) = 4.8e-13;
Gstr{i,1} = 'ETHPYRS';Gstr{i,2} = 'NO3';
fETHPYRS(i)=fETHPYRS(i)-1; fNO3(i)=fNO3(i)-1; fPPETHPYRS(i)=fPPETHPYRS(i)+1; 
 
 
i=i+1;
Rnames{i} = 'ETHSYTRENE + NO3 = PPETHSYTRENE';
k(:,i) = 1.51e-12;
Gstr{i,1} = 'ETHSYTRENE';Gstr{i,2} = 'NO3';
fETHSYTRENE(i)=fETHSYTRENE(i)-1; fNO3(i)=fNO3(i)-1; fPPETHSYTRENE(i)=fPPETHSYTRENE(i)+1; 
 
 
i=i+1;
Rnames{i} = 'ETPYRROLE + NO3 = PPETPYRROLE';
k(:,i) = 4.6e-11;
Gstr{i,1} = 'ETPYRROLE';Gstr{i,2} = 'NO3';
fETPYRROLE(i)=fETPYRROLE(i)-1; fNO3(i)=fNO3(i)-1; fPPETPYRROLE(i)=fPPETPYRROLE(i)+1; 
 
 
i=i+1;
Rnames{i} = 'ETYNPYRROLE + NO3 = PPETYNPYRROLE';
k(:,i) = 4.6e-11;
Gstr{i,1} = 'ETYNPYRROLE';Gstr{i,2} = 'NO3';
fETYNPYRROLE(i)=fETYNPYRROLE(i)-1; fNO3(i)=fNO3(i)-1; fPPETYNPYRROLE(i)=fPPETYNPYRROLE(i)+1; 
 
 
i=i+1;
Rnames{i} = 'EVK + NO3 = PPEVK';
k(:,i) = 2.45e-16;
Gstr{i,1} = 'EVK';Gstr{i,2} = 'NO3';
fEVK(i)=fEVK(i)-1; fNO3(i)=fNO3(i)-1; fPPEVK(i)=fPPEVK(i)+1; 
 
 
i=i+1;
Rnames{i} = 'EZOCIMENE + NO3 = PPEZOCIMENE';
k(:,i) = 2.2e-11;
Gstr{i,1} = 'EZOCIMENE';Gstr{i,2} = 'NO3';
fEZOCIMENE(i)=fEZOCIMENE(i)-1; fNO3(i)=fNO3(i)-1; fPPEZOCIMENE(i)=fPPEZOCIMENE(i)+1; 
 
 
i=i+1;
Rnames{i} = 'FURAN + NO3 = PPFURAN';
%k(:,i) = 1.3e-12;
k(:,i) = 1.2e-12;
Gstr{i,1} = 'FURAN';Gstr{i,2} = 'NO3';
fFURAN(i)=fFURAN(i)-1; fNO3(i)=fNO3(i)-1; fPPFURAN(i)=fPPFURAN(i)+1; 
 
 
i=i+1;
Rnames{i} = 'FURAN23DIHYD + NO3 = PPFURAN23DIHYD';
k(:,i) = 4.97e-11;
Gstr{i,1} = 'FURAN23DIHYD';Gstr{i,2} = 'NO3';
fFURAN23DIHYD(i)=fFURAN23DIHYD(i)-1; fNO3(i)=fNO3(i)-1; fPPFURAN23DIHYD(i)=fPPFURAN23DIHYD(i)+1; 
 
 
i=i+1;
Rnames{i} = 'FURAN25DIHYD + NO3 = PPFURAN25DIHYD';
k(:,i) = 4.97e-11;
Gstr{i,1} = 'FURAN25DIHYD';Gstr{i,2} = 'NO3';
fFURAN25DIHYD(i)=fFURAN25DIHYD(i)-1; fNO3(i)=fNO3(i)-1; fPPFURAN25DIHYD(i)=fPPFURAN25DIHYD(i)+1; 
 
 
i=i+1;
Rnames{i} = 'FURANTETHYD + NO3 = PPFURANTETHYD';
k(:,i) = 3.08e-15;
Gstr{i,1} = 'FURANTETHYD';Gstr{i,2} = 'NO3';
fFURANTETHYD(i)=fFURANTETHYD(i)-1; fNO3(i)=fNO3(i)-1; fPPFURANTETHYD(i)=fPPFURANTETHYD(i)+1; 
 
 
i=i+1;
Rnames{i} = 'FURCARBCN2 + NO3 = PPFURCARBCN2';
k(:,i) = 1.3e-11;
Gstr{i,1} = 'FURCARBCN2';Gstr{i,2} = 'NO3';
fFURCARBCN2(i)=fFURCARBCN2(i)-1; fNO3(i)=fNO3(i)-1; fPPFURCARBCN2(i)=fPPFURCARBCN2(i)+1; 
 
 
i=i+1;
Rnames{i} = 'FURCARBCN3 + NO3 = PPFURCARBCN3';
k(:,i) = 1.3e-11;
Gstr{i,1} = 'FURCARBCN3';Gstr{i,2} = 'NO3';
fFURCARBCN3(i)=fFURCARBCN3(i)-1; fNO3(i)=fNO3(i)-1; fPPFURCARBCN3(i)=fPPFURCARBCN3(i)+1; 
 
 
i=i+1;
Rnames{i} = 'FURFURAL + NO3 = PPFURFURAL';
k(:,i) = 1.2e-12;
Gstr{i,1} = 'FURFURAL';Gstr{i,2} = 'NO3';
fFURFURAL(i)=fFURFURAL(i)-1; fNO3(i)=fNO3(i)-1; fPPFURFURAL(i)=fPPFURFURAL(i)+1; 
 
 
i=i+1;
Rnames{i} = 'FURFURAL3 + NO3 = PPFURFURAL3';
k(:,i) = 3.41e-12;
Gstr{i,1} = 'FURFURAL3';Gstr{i,2} = 'NO3';
fFURFURAL3(i)=fFURFURAL3(i)-1; fNO3(i)=fNO3(i)-1; fPPFURFURAL3(i)=fPPFURFURAL3(i)+1; 
 
 
i=i+1;
Rnames{i} = 'H2S + NO3 = PPH2S';
k(:,i) = 1e-15;
Gstr{i,1} = 'H2S';Gstr{i,2} = 'NO3';
fH2S(i)=fH2S(i)-1; fNO3(i)=fNO3(i)-1; fPPH2S(i)=fPPH2S(i)+1; 
 
 
i=i+1;
Rnames{i} = 'HCN + NO3 = PPHCN';
k(:,i) = 1e-18;
Gstr{i,1} = 'HCN';Gstr{i,2} = 'NO3';
fHCN(i)=fHCN(i)-1; fNO3(i)=fNO3(i)-1; fPPHCN(i)=fPPHCN(i)+1; 
 
 
i=i+1;
Rnames{i} = 'HCONH2 + NO3 = PPHCONH2';
k(:,i) = 4.9e-14;
Gstr{i,1} = 'HCONH2';Gstr{i,2} = 'NO3';
fHCONH2(i)=fHCONH2(i)-1; fNO3(i)=fNO3(i)-1; fPPHCONH2(i)=fPPHCONH2(i)+1; 
 
 
i=i+1;
Rnames{i} = 'HCOOH + NO3 = PPHCOOH';
k(:,i) = 1e-17;
Gstr{i,1} = 'HCOOH';Gstr{i,2} = 'NO3';
fHCOOH(i)=fHCOOH(i)-1; fNO3(i)=fNO3(i)-1; fPPHCOOH(i)=fPPHCOOH(i)+1; 
 
 
i=i+1;
Rnames{i} = 'HEPT16DIEN + NO3 = PPHEPT16DIEN';
k(:,i) = 4.94e-13;
Gstr{i,1} = 'HEPT16DIEN';Gstr{i,2} = 'NO3';
fHEPT16DIEN(i)=fHEPT16DIEN(i)-1; fNO3(i)=fNO3(i)-1; fPPHEPT16DIEN(i)=fPPHEPT16DIEN(i)+1; 
 
 
i=i+1;
Rnames{i} = 'HEPT3ONE + NO3 = PPHEPT3ONE';
k(:,i) = 1e-15;
Gstr{i,1} = 'HEPT3ONE';Gstr{i,2} = 'NO3';
fHEPT3ONE(i)=fHEPT3ONE(i)-1; fNO3(i)=fNO3(i)-1; fPPHEPT3ONE(i)=fPPHEPT3ONE(i)+1; 
 
 
i=i+1;
Rnames{i} = 'HEPTCNS + NO3 = PPHEPTCNS';
k(:,i) = 1e-18;
Gstr{i,1} = 'HEPTCNS';Gstr{i,2} = 'NO3';
fHEPTCNS(i)=fHEPTCNS(i)-1; fNO3(i)=fNO3(i)-1; fPPHEPTCNS(i)=fPPHEPTCNS(i)+1; 
 
 
i=i+1;
Rnames{i} = 'HEPTEN + NO3 = PPHEPTEN';
k(:,i) = 2.1e-14;
Gstr{i,1} = 'HEPTEN';Gstr{i,2} = 'NO3';
fHEPTEN(i)=fHEPTEN(i)-1; fNO3(i)=fNO3(i)-1; fPPHEPTEN(i)=fPPHEPTEN(i)+1; 
 
 
i=i+1;
Rnames{i} = 'HEX13DIEN + NO3 = PPHEX13DIEN';
k(:,i) = 2.96e-12;
Gstr{i,1} = 'HEX13DIEN';Gstr{i,2} = 'NO3';
fHEX13DIEN(i)=fHEX13DIEN(i)-1; fNO3(i)=fNO3(i)-1; fPPHEX13DIEN(i)=fPPHEX13DIEN(i)+1; 
 
 
i=i+1;
Rnames{i} = 'HEX14DIEN + NO3 = PPHEX14DIEN';
k(:,i) = 2.96e-12;
Gstr{i,1} = 'HEX14DIEN';Gstr{i,2} = 'NO3';
fHEX14DIEN(i)=fHEX14DIEN(i)-1; fNO3(i)=fNO3(i)-1; fPPHEX14DIEN(i)=fPPHEX14DIEN(i)+1; 
 
 
i=i+1;
Rnames{i} = 'HEX15DI3YN + NO3 = PPHEX15DI3YN';
k(:,i) = 2.96e-12;
Gstr{i,1} = 'HEX15DI3YN';Gstr{i,2} = 'NO3';
fHEX15DI3YN(i)=fHEX15DI3YN(i)-1; fNO3(i)=fNO3(i)-1; fPPHEX15DI3YN(i)=fPPHEX15DI3YN(i)+1; 
 
 
i=i+1;
Rnames{i} = 'HEX1EN3YN + NO3 = PPHEX1EN3YN';
k(:,i) = 2e-14;
Gstr{i,1} = 'HEX1EN3YN';Gstr{i,2} = 'NO3';
fHEX1EN3YN(i)=fHEX1EN3YN(i)-1; fNO3(i)=fNO3(i)-1; fPPHEX1EN3YN(i)=fPPHEX1EN3YN(i)+1; 
 
 
i=i+1;
Rnames{i} = 'HEX2EN4YN + NO3 = PPHEX2EN4YN';
k(:,i) = 2e-14;
Gstr{i,1} = 'HEX2EN4YN';Gstr{i,2} = 'NO3';
fHEX2EN4YN(i)=fHEX2EN4YN(i)-1; fNO3(i)=fNO3(i)-1; fPPHEX2EN4YN(i)=fPPHEX2EN4YN(i)+1; 
 
 
i=i+1;
Rnames{i} = 'HEX2ENE + NO3 = PPHEX2ENE';
k(:,i) = 4.57e-13;
Gstr{i,1} = 'HEX2ENE';Gstr{i,2} = 'NO3';
fHEX2ENE(i)=fHEX2ENE(i)-1; fNO3(i)=fNO3(i)-1; fPPHEX2ENE(i)=fPPHEX2ENE(i)+1; 
 
 
i=i+1;
Rnames{i} = 'HEX2ONE + NO3 = PPHEX2ONE';
k(:,i) = 1e-15;
Gstr{i,1} = 'HEX2ONE';Gstr{i,2} = 'NO3';
fHEX2ONE(i)=fHEX2ONE(i)-1; fNO3(i)=fNO3(i)-1; fPPHEX2ONE(i)=fPPHEX2ONE(i)+1; 
 
 
i=i+1;
Rnames{i} = 'HEX3ONE + NO3 = PPHEX3ONE';
k(:,i) = 1e-15;
Gstr{i,1} = 'HEX3ONE';Gstr{i,2} = 'NO3';
fHEX3ONE(i)=fHEX3ONE(i)-1; fNO3(i)=fNO3(i)-1; fPPHEX3ONE(i)=fPPHEX3ONE(i)+1; 
 
 
i=i+1;
Rnames{i} = 'HEX3YN + NO3 = PPHEX3YN';
k(:,i) = 2.81e-14;
Gstr{i,1} = 'HEX3YN';Gstr{i,2} = 'NO3';
fHEX3YN(i)=fHEX3YN(i)-1; fNO3(i)=fNO3(i)-1; fPPHEX3YN(i)=fPPHEX3YN(i)+1; 
 
 
i=i+1;
Rnames{i} = 'HEXE14DIEN + NO3 = PPHEXE14DIEN';
k(:,i) = 2.96e-12;
Gstr{i,1} = 'HEXE14DIEN';Gstr{i,2} = 'NO3';
fHEXE14DIEN(i)=fHEXE14DIEN(i)-1; fNO3(i)=fNO3(i)-1; fPPHEXE14DIEN(i)=fPPHEXE14DIEN(i)+1; 
 
 
i=i+1;
Rnames{i} = 'HEXEE24DIEN + NO3 = PPHEXEE24DIEN';
k(:,i) = 1.6e-12;
Gstr{i,1} = 'HEXEE24DIEN';Gstr{i,2} = 'NO3';
fHEXEE24DIEN(i)=fHEXEE24DIEN(i)-1; fNO3(i)=fNO3(i)-1; fPPHEXEE24DIEN(i)=fPPHEXEE24DIEN(i)+1; 
 
 
i=i+1;
Rnames{i} = 'HEXEE24DIENAL + NO3 = PPHEXEE24DIENAL';
k(:,i) = 8.18e-12;
Gstr{i,1} = 'HEXEE24DIENAL';Gstr{i,2} = 'NO3';
fHEXEE24DIENAL(i)=fHEXEE24DIENAL(i)-1; fNO3(i)=fNO3(i)-1; fPPHEXEE24DIENAL(i)=fPPHEXEE24DIENAL(i)+1; 
 
 
i=i+1;
Rnames{i} = 'HEXEX24DIEN + NO3 = PPHEXEX24DIEN';
k(:,i) = 7.42e-12;
Gstr{i,1} = 'HEXEX24DIEN';Gstr{i,2} = 'NO3';
fHEXEX24DIEN(i)=fHEXEX24DIEN(i)-1; fNO3(i)=fNO3(i)-1; fPPHEXEX24DIEN(i)=fPPHEXEX24DIEN(i)+1; 
 
 
i=i+1;
Rnames{i} = 'HNCO + NO3 = PPHNCO';
k(:,i) = 1e-17;
Gstr{i,1} = 'HNCO';Gstr{i,2} = 'NO3';
fHNCO(i)=fHNCO(i)-1; fNO3(i)=fNO3(i)-1; fPPHNCO(i)=fPPHNCO(i)+1; 
 
 
i=i+1;
Rnames{i} = 'HONO + NO3 = PPHONO';
k(:,i) = 2e-15;
Gstr{i,1} = 'HONO';Gstr{i,2} = 'NO3';
fHONO(i)=fHONO(i)-1; fNO3(i)=fNO3(i)-1; fPPHONO(i)=fPPHONO(i)+1; 
 
 
i=i+1;
Rnames{i} = 'HYBENZQUIN + NO3 = PPHYBENZQUIN';
k(:,i) = 3e-13;
Gstr{i,1} = 'HYBENZQUIN';Gstr{i,2} = 'NO3';
fHYBENZQUIN(i)=fHYBENZQUIN(i)-1; fNO3(i)=fNO3(i)-1; fPPHYBENZQUIN(i)=fPPHYBENZQUIN(i)+1; 
 
 
i=i+1;
Rnames{i} = 'HYDROXCN + NO3 = PPHYDROXCN';
k(:,i) = 1e-18;
Gstr{i,1} = 'HYDROXCN';Gstr{i,2} = 'NO3';
fHYDROXCN(i)=fHYDROXCN(i)-1; fNO3(i)=fNO3(i)-1; fPPHYDROXCN(i)=fPPHYDROXCN(i)+1; 
 
 
i=i+1;
Rnames{i} = 'INDANE + NO3 = PPINDANE';
k(:,i) = 6.6e-15;
Gstr{i,1} = 'INDANE';Gstr{i,2} = 'NO3';
fINDANE(i)=fINDANE(i)-1; fNO3(i)=fNO3(i)-1; fPPINDANE(i)=fPPINDANE(i)+1; 
 
 
i=i+1;
Rnames{i} = 'INDENE + NO3 = PPINDENE';
k(:,i) = 4.1e-12;
Gstr{i,1} = 'INDENE';Gstr{i,2} = 'NO3';
fINDENE(i)=fINDENE(i)-1; fNO3(i)=fNO3(i)-1; fPPINDENE(i)=fPPINDENE(i)+1; 
 
 
i=i+1;
Rnames{i} = 'IPROPOL + NO3 = PPIPROPOL';
k(:,i) = 1.4e-15;
Gstr{i,1} = 'IPROPOL';Gstr{i,2} = 'NO3';
fIPROPOL(i)=fIPROPOL(i)-1; fNO3(i)=fNO3(i)-1; fPPIPROPOL(i)=fPPIPROPOL(i)+1; 
 
 
i=i+1;
Rnames{i} = 'ISOBUTCN + NO3 = PPISOBUTCN';
k(:,i) = 1e-18;
Gstr{i,1} = 'ISOBUTCN';Gstr{i,2} = 'NO3';
fISOBUTCN(i)=fISOBUTCN(i)-1; fNO3(i)=fNO3(i)-1; fPPISOBUTCN(i)=fPPISOBUTCN(i)+1; 
 
 
i=i+1;
Rnames{i} = 'ISOEUGOL + NO3 = PPISOEUGOL';
k(:,i) = 1.6e-13;
Gstr{i,1} = 'ISOEUGOL';Gstr{i,2} = 'NO3';
fISOEUGOL(i)=fISOEUGOL(i)-1; fNO3(i)=fNO3(i)-1; fPPISOEUGOL(i)=fPPISOEUGOL(i)+1; 
 
 
i=i+1;
Rnames{i} = 'M1CYHEXEN + NO3 = PPM1CYHEXEN';
k(:,i) = 9.7e-12;
Gstr{i,1} = 'M1CYHEXEN';Gstr{i,2} = 'NO3';
fM1CYHEXEN(i)=fM1CYHEXEN(i)-1; fNO3(i)=fNO3(i)-1; fPPM1CYHEXEN(i)=fPPM1CYHEXEN(i)+1; 
 
 
i=i+1;
Rnames{i} = 'M1CYPENEN + NO3 = PPM1CYPENEN';
k(:,i) = 8.15e-12;
Gstr{i,1} = 'M1CYPENEN';Gstr{i,2} = 'NO3';
fM1CYPENEN(i)=fM1CYPENEN(i)-1; fNO3(i)=fNO3(i)-1; fPPM1CYPENEN(i)=fPPM1CYPENEN(i)+1; 
 
 
i=i+1;
Rnames{i} = 'M1CYPENT13DIEN + NO3 = PPM1CYPENT13DIEN';
k(:,i) = 4.07e-12;
Gstr{i,1} = 'M1CYPENT13DIEN';Gstr{i,2} = 'NO3';
fM1CYPENT13DIEN(i)=fM1CYPENT13DIEN(i)-1; fNO3(i)=fNO3(i)-1; fPPM1CYPENT13DIEN(i)=fPPM1CYPENT13DIEN(i)+1; 
 
 
i=i+1;
Rnames{i} = 'M2BK + NO3 = PPM2BK';
k(:,i) = 1.11e-16;
Gstr{i,1} = 'M2BK';Gstr{i,2} = 'NO3';
fM2BK(i)=fM2BK(i)-1; fNO3(i)=fNO3(i)-1; fPPM2BK(i)=fPPM2BK(i)+1; 
 
 
i=i+1;
Rnames{i} = 'M2BUT1EN3YN + NO3 = PPM2BUT1EN3YN';
k(:,i) = 6.9e-14;
Gstr{i,1} = 'M2BUT1EN3YN';Gstr{i,2} = 'NO3';
fM2BUT1EN3YN(i)=fM2BUT1EN3YN(i)-1; fNO3(i)=fNO3(i)-1; fPPM2BUT1EN3YN(i)=fPPM2BUT1EN3YN(i)+1; 
 
 
i=i+1;
Rnames{i} = 'M2BUTANAL + NO3 = PPM2BUTANAL';
k(:,i) = 2.58e-16;
Gstr{i,1} = 'M2BUTANAL';Gstr{i,2} = 'NO3';
fM2BUTANAL(i)=fM2BUTANAL(i)-1; fNO3(i)=fNO3(i)-1; fPPM2BUTANAL(i)=fPPM2BUTANAL(i)+1; 
 
 
i=i+1;
Rnames{i} = 'M2BUTCN + NO3 = PPM2BUTCN';
k(:,i) = 1e-18;
Gstr{i,1} = 'M2BUTCN';Gstr{i,2} = 'NO3';
fM2BUTCN(i)=fM2BUTCN(i)-1; fNO3(i)=fNO3(i)-1; fPPM2BUTCN(i)=fPPM2BUTCN(i)+1; 
 
 
i=i+1;
Rnames{i} = 'M2CYPENT2EN1ON + NO3 = PPM2CYPENT2EN1ON';
k(:,i) = 1.92e-12;
Gstr{i,1} = 'M2CYPENT2EN1ON';Gstr{i,2} = 'NO3';
fM2CYPENT2EN1ON(i)=fM2CYPENT2EN1ON(i)-1; fNO3(i)=fNO3(i)-1; fPPM2CYPENT2EN1ON(i)=fPPM2CYPENT2EN1ON(i)+1; 
 
 
i=i+1;
Rnames{i} = 'M2CYPENTON + NO3 = PPM2CYPENTON';
k(:,i) = 8.67e-17;
Gstr{i,1} = 'M2CYPENTON';Gstr{i,2} = 'NO3';
fM2CYPENTON(i)=fM2CYPENTON(i)-1; fNO3(i)=fNO3(i)-1; fPPM2CYPENTON(i)=fPPM2CYPENTON(i)+1; 
 
 
i=i+1;
Rnames{i} = 'M2FURAN + NO3 = PPM2FURAN';
k(:,i) = 2.57e-11;
Gstr{i,1} = 'M2FURAN';Gstr{i,2} = 'NO3';
fM2FURAN(i)=fM2FURAN(i)-1; fNO3(i)=fNO3(i)-1; fPPM2FURAN(i)=fPPM2FURAN(i)+1; 
 
 
i=i+1;
Rnames{i} = 'M2OLFURAN + NO3 = PPM2OLFURAN';
k(:,i) = 1.3e-11;
Gstr{i,1} = 'M2OLFURAN';Gstr{i,2} = 'NO3';
fM2OLFURAN(i)=fM2OLFURAN(i)-1; fNO3(i)=fNO3(i)-1; fPPM2OLFURAN(i)=fPPM2OLFURAN(i)+1; 
 
 
i=i+1;
Rnames{i} = 'M2PENT14DIEN + NO3 = PPM2PENT14DIEN';
k(:,i) = 2.96e-12;
Gstr{i,1} = 'M2PENT14DIEN';Gstr{i,2} = 'NO3';
fM2PENT14DIEN(i)=fM2PENT14DIEN(i)-1; fNO3(i)=fNO3(i)-1; fPPM2PENT14DIEN(i)=fPPM2PENT14DIEN(i)+1; 
 
 
i=i+1;
Rnames{i} = 'M2PENT2EN + NO3 = PPM2PENT2EN';
k(:,i) = 8.9e-12;
Gstr{i,1} = 'M2PENT2EN';Gstr{i,2} = 'NO3';
fM2PENT2EN(i)=fM2PENT2EN(i)-1; fNO3(i)=fNO3(i)-1; fPPM2PENT2EN(i)=fPPM2PENT2EN(i)+1; 
 
 
i=i+1;
Rnames{i} = 'M2PENTE13DIEN + NO3 = PPM2PENTE13DIEN';
k(:,i) = 2.96e-12;
Gstr{i,1} = 'M2PENTE13DIEN';Gstr{i,2} = 'NO3';
fM2PENTE13DIEN(i)=fM2PENTE13DIEN(i)-1; fNO3(i)=fNO3(i)-1; fPPM2PENTE13DIEN(i)=fPPM2PENTE13DIEN(i)+1; 
 
 
i=i+1;
Rnames{i} = 'M2PENTZ13DIEN + NO3 = PPM2PENTZ13DIEN';
k(:,i) = 2.96e-12;
Gstr{i,1} = 'M2PENTZ13DIEN';Gstr{i,2} = 'NO3';
fM2PENTZ13DIEN(i)=fM2PENTZ13DIEN(i)-1; fNO3(i)=fNO3(i)-1; fPPM2PENTZ13DIEN(i)=fPPM2PENTZ13DIEN(i)+1; 
 
 
i=i+1;
Rnames{i} = 'M3BUTCN + NO3 = PPM3BUTCN';
k(:,i) = 1e-18;
Gstr{i,1} = 'M3BUTCN';Gstr{i,2} = 'NO3';
fM3BUTCN(i)=fM3BUTCN(i)-1; fNO3(i)=fNO3(i)-1; fPPM3BUTCN(i)=fPPM3BUTCN(i)+1; 
 
 
i=i+1;
Rnames{i} = 'M3CO5C6 + NO3 = PPM3CO5C6';
k(:,i) = 1e-15;
Gstr{i,1} = 'M3CO5C6';Gstr{i,2} = 'NO3';
fM3CO5C6(i)=fM3CO5C6(i)-1; fNO3(i)=fNO3(i)-1; fPPM3CO5C6(i)=fPPM3CO5C6(i)+1; 
 
 
i=i+1;
Rnames{i} = 'M3CYHEXEN + NO3 = PPM3CYHEXEN';
k(:,i) = 9.7e-12;
Gstr{i,1} = 'M3CYHEXEN';Gstr{i,2} = 'NO3';
fM3CYHEXEN(i)=fM3CYHEXEN(i)-1; fNO3(i)=fNO3(i)-1; fPPM3CYHEXEN(i)=fPPM3CYHEXEN(i)+1; 
 
 
i=i+1;
Rnames{i} = 'M3CYPENT2EN1ON + NO3 = PPM3CYPENT2EN1ON';
k(:,i) = 1.92e-13;
Gstr{i,1} = 'M3CYPENT2EN1ON';Gstr{i,2} = 'NO3';
fM3CYPENT2EN1ON(i)=fM3CYPENT2EN1ON(i)-1; fNO3(i)=fNO3(i)-1; fPPM3CYPENT2EN1ON(i)=fPPM3CYPENT2EN1ON(i)+1; 
 
 
i=i+1;
Rnames{i} = 'M3CYPENTEN + NO3 = PPM3CYPENTEN';
k(:,i) = 8.15e-12;
Gstr{i,1} = 'M3CYPENTEN';Gstr{i,2} = 'NO3';
fM3CYPENTEN(i)=fM3CYPENTEN(i)-1; fNO3(i)=fNO3(i)-1; fPPM3CYPENTEN(i)=fPPM3CYPENTEN(i)+1; 
 
 
i=i+1;
Rnames{i} = 'M3ETH2BUT1EN + NO3 = PPM3ETH2BUT1EN';
k(:,i) = 3.79e-13;
Gstr{i,1} = 'M3ETH2BUT1EN';Gstr{i,2} = 'NO3';
fM3ETH2BUT1EN(i)=fM3ETH2BUT1EN(i)-1; fNO3(i)=fNO3(i)-1; fPPM3ETH2BUT1EN(i)=fPPM3ETH2BUT1EN(i)+1; 
 
 
i=i+1;
Rnames{i} = 'M3PENTE2EN + NO3 = PPM3PENTE2EN';
k(:,i) = 8.9e-12;
Gstr{i,1} = 'M3PENTE2EN';Gstr{i,2} = 'NO3';
fM3PENTE2EN(i)=fM3PENTE2EN(i)-1; fNO3(i)=fNO3(i)-1; fPPM3PENTE2EN(i)=fPPM3PENTE2EN(i)+1; 
 
 
i=i+1;
Rnames{i} = 'M3PENTZ13DIEN + NO3 = PPM3PENTZ13DIEN';
k(:,i) = 5.38e-12;
Gstr{i,1} = 'M3PENTZ13DIEN';Gstr{i,2} = 'NO3';
fM3PENTZ13DIEN(i)=fM3PENTZ13DIEN(i)-1; fNO3(i)=fNO3(i)-1; fPPM3PENTZ13DIEN(i)=fPPM3PENTZ13DIEN(i)+1; 
 
 
i=i+1;
Rnames{i} = 'M3PENTZ2EN + NO3 = PPM3PENTZ2EN';
k(:,i) = 2.69e-12;
Gstr{i,1} = 'M3PENTZ2EN';Gstr{i,2} = 'NO3';
fM3PENTZ2EN(i)=fM3PENTZ2EN(i)-1; fNO3(i)=fNO3(i)-1; fPPM3PENTZ2EN(i)=fPPM3PENTZ2EN(i)+1; 
 
 
i=i+1;
Rnames{i} = 'M4CYHEX4EN + NO3 = PPM4CYHEX4EN';
k(:,i) = 4.5e-13;
Gstr{i,1} = 'M4CYHEX4EN';Gstr{i,2} = 'NO3';
fM4CYHEX4EN(i)=fM4CYHEX4EN(i)-1; fNO3(i)=fNO3(i)-1; fPPM4CYHEX4EN(i)=fPPM4CYHEX4EN(i)+1; 
 
 
i=i+1;
Rnames{i} = 'M4PENT13DIEN + NO3 = PPM4PENT13DIEN';
k(:,i) = 5.38e-12;
Gstr{i,1} = 'M4PENT13DIEN';Gstr{i,2} = 'NO3';
fM4PENT13DIEN(i)=fM4PENT13DIEN(i)-1; fNO3(i)=fNO3(i)-1; fPPM4PENT13DIEN(i)=fPPM4PENT13DIEN(i)+1; 
 
 
i=i+1;
Rnames{i} = 'M4PENT1EN + NO3 = PPM4PENT1EN';
k(:,i) = 4.27e-14;
Gstr{i,1} = 'M4PENT1EN';Gstr{i,2} = 'NO3';
fM4PENT1EN(i)=fM4PENT1EN(i)-1; fNO3(i)=fNO3(i)-1; fPPM4PENT1EN(i)=fPPM4PENT1EN(i)+1; 
 
 
i=i+1;
Rnames{i} = 'M5CYPENT13DIEN + NO3 = PPM5CYPENT13DIEN';
k(:,i) = 7.92e-12;
Gstr{i,1} = 'M5CYPENT13DIEN';Gstr{i,2} = 'NO3';
fM5CYPENT13DIEN(i)=fM5CYPENT13DIEN(i)-1; fNO3(i)=fNO3(i)-1; fPPM5CYPENT13DIEN(i)=fPPM5CYPENT13DIEN(i)+1; 
 
 
i=i+1;
Rnames{i} = 'M5FURAN23DIHY + NO3 = PPM5FURAN23DIHY';
k(:,i) = 1.68e-10;
Gstr{i,1} = 'M5FURAN23DIHY';Gstr{i,2} = 'NO3';
fM5FURAN23DIHY(i)=fM5FURAN23DIHY(i)-1; fNO3(i)=fNO3(i)-1; fPPM5FURAN23DIHY(i)=fPPM5FURAN23DIHY(i)+1; 
 
 
i=i+1;
Rnames{i} = 'M5PENT2EN + NO3 = PPM5PENT2EN';
k(:,i) = 3.72e-13;
Gstr{i,1} = 'M5PENT2EN';Gstr{i,2} = 'NO3';
fM5PENT2EN(i)=fM5PENT2EN(i)-1; fNO3(i)=fNO3(i)-1; fPPM5PENT2EN(i)=fPPM5PENT2EN(i)+1; 
 
 
i=i+1;
Rnames{i} = 'MACRYLATE + NO3 = PPMACRYLATE';
k(:,i) = 1.9e-16;
Gstr{i,1} = 'MACRYLATE';Gstr{i,2} = 'NO3';
fMACRYLATE(i)=fMACRYLATE(i)-1; fNO3(i)=fNO3(i)-1; fPPMACRYLATE(i)=fPPMACRYLATE(i)+1; 
 
 
i=i+1;
Rnames{i} = 'MACRYLCN + NO3 = PPMACRYLCN';
k(:,i) = 5.15e-13;
Gstr{i,1} = 'MACRYLCN';Gstr{i,2} = 'NO3';
fMACRYLCN(i)=fMACRYLCN(i)-1; fNO3(i)=fNO3(i)-1; fPPMACRYLCN(i)=fPPMACRYLCN(i)+1; 
 
 
i=i+1;
Rnames{i} = 'MANIMINE + NO3 = PPMANIMINE';
k(:,i) = 7e-14;
Gstr{i,1} = 'MANIMINE';Gstr{i,2} = 'NO3';
fMANIMINE(i)=fMANIMINE(i)-1; fNO3(i)=fNO3(i)-1; fPPMANIMINE(i)=fPPMANIMINE(i)+1; 
 
 
i=i+1;
Rnames{i} = 'MANISOLE + NO3 = PPMANISOLE';
k(:,i) = 9.45e-17;
Gstr{i,1} = 'MANISOLE';Gstr{i,2} = 'NO3';
fMANISOLE(i)=fMANISOLE(i)-1; fNO3(i)=fNO3(i)-1; fPPMANISOLE(i)=fPPMANISOLE(i)+1; 
 
 
i=i+1;
Rnames{i} = 'MBENZACETO + NO3 = PPMBENZACETO';
k(:,i) = 6.79e-17;
Gstr{i,1} = 'MBENZACETO';Gstr{i,2} = 'NO3';
fMBENZACETO(i)=fMBENZACETO(i)-1; fNO3(i)=fNO3(i)-1; fPPMBENZACETO(i)=fPPMBENZACETO(i)+1; 
 
 
i=i+1;
Rnames{i} = 'MBENZAL + NO3 = PPMBENZAL';
k(:,i) = 2.4e-15;
Gstr{i,1} = 'MBENZAL';Gstr{i,2} = 'NO3';
fMBENZAL(i)=fMBENZAL(i)-1; fNO3(i)=fNO3(i)-1; fPPMBENZAL(i)=fPPMBENZAL(i)+1; 
 
 
i=i+1;
Rnames{i} = 'MCHAVICOL + NO3 = PPMCHAVICOL';
k(:,i) = 3.75e-14;
Gstr{i,1} = 'MCHAVICOL';Gstr{i,2} = 'NO3';
fMCHAVICOL(i)=fMCHAVICOL(i)-1; fNO3(i)=fNO3(i)-1; fPPMCHAVICOL(i)=fPPMCHAVICOL(i)+1; 
 
 
i=i+1;
Rnames{i} = 'MCYPENTONES + NO3 = PPMCYPENTONES';
k(:,i) = 1e-15;
Gstr{i,1} = 'MCYPENTONES';Gstr{i,2} = 'NO3';
fMCYPENTONES(i)=fMCYPENTONES(i)-1; fNO3(i)=fNO3(i)-1; fPPMCYPENTONES(i)=fPPMCYPENTONES(i)+1; 
 
 
i=i+1;
Rnames{i} = 'MEK + NO3 = PPMEK';
k(:,i) = 2.51e-15;
Gstr{i,1} = 'MEK';Gstr{i,2} = 'NO3';
fMEK(i)=fMEK(i)-1; fNO3(i)=fNO3(i)-1; fPPMEK(i)=fPPMEK(i)+1; 
 
 
i=i+1;
Rnames{i} = 'MEKCOH + NO3 = PPMEKCOH';
k(:,i) = 9e-16;
Gstr{i,1} = 'MEKCOH';Gstr{i,2} = 'NO3';
fMEKCOH(i)=fMEKCOH(i)-1; fNO3(i)=fNO3(i)-1; fPPMEKCOH(i)=fPPMEKCOH(i)+1; 
 
 
i=i+1;
Rnames{i} = 'MESTPROPACD + NO3 = PPMESTPROPACD';
k(:,i) = 9e-17;
Gstr{i,1} = 'MESTPROPACD';Gstr{i,2} = 'NO3';
fMESTPROPACD(i)=fMESTPROPACD(i)-1; fNO3(i)=fNO3(i)-1; fPPMESTPROPACD(i)=fPPMESTPROPACD(i)+1; 
 
 
i=i+1;
Rnames{i} = 'METHACET + NO3 = PPMETHACET';
k(:,i) = 7e-18;
Gstr{i,1} = 'METHACET';Gstr{i,2} = 'NO3';
fMETHACET(i)=fMETHACET(i)-1; fNO3(i)=fNO3(i)-1; fPPMETHACET(i)=fPPMETHACET(i)+1; 
 
 
i=i+1;
Rnames{i} = 'MEFURFURAL + NO3 = PPMEFURFURAL';
k(:,i) = 5.51e-12;
Gstr{i,1} = 'MEFURFURAL';Gstr{i,2} = 'NO3';
fMEFURFURAL(i)=fMEFURFURAL(i)-1; fNO3(i)=fNO3(i)-1; fPPMEFURFURAL(i)=fPPMEFURFURAL(i)+1; 
 
 
i=i+1;
Rnames{i} = 'MIBK + NO3 = PPMIBK';
k(:,i) = 1.36e-16;
Gstr{i,1} = 'MIBK';Gstr{i,2} = 'NO3';
fMIBK(i)=fMIBK(i)-1; fNO3(i)=fNO3(i)-1; fPPMIBK(i)=fPPMIBK(i)+1; 
 
 
i=i+1;
Rnames{i} = 'MIPK + NO3 = PPMIPK';
k(:,i) = 5e-16;
Gstr{i,1} = 'MIPK';Gstr{i,2} = 'NO3';
fMIPK(i)=fMIPK(i)-1; fNO3(i)=fNO3(i)-1; fPPMIPK(i)=fPPMIPK(i)+1; 
 
 
i=i+1;
Rnames{i} = 'MMALIDE + NO3 = PPMMALIDE';
k(:,i) = 1.02e-13;
Gstr{i,1} = 'MMALIDE';Gstr{i,2} = 'NO3';
fMMALIDE(i)=fMMALIDE(i)-1; fNO3(i)=fNO3(i)-1; fPPMMALIDE(i)=fPPMMALIDE(i)+1; 
 
 
i=i+1;
Rnames{i} = 'MMETACRL + NO3 = PPMMETACRL';
k(:,i) = 3.6e-15;
Gstr{i,1} = 'MMETACRL';Gstr{i,2} = 'NO3';
fMMETACRL(i)=fMMETACRL(i)-1; fNO3(i)=fNO3(i)-1; fPPMMETACRL(i)=fPPMMETACRL(i)+1; 
 
 
i=i+1;
Rnames{i} = 'MNAPT + NO3 = PPMNAPT';
k(:,i) = 2e-11;
Gstr{i,1} = 'MNAPT';Gstr{i,2} = 'NO3';
fMNAPT(i)=fMNAPT(i)-1; fNO3(i)=fNO3(i)-1; fPPMNAPT(i)=fPPMNAPT(i)+1; 
 
 
i=i+1;
Rnames{i} = 'MOXYHYFUR + NO3 = PPMOXYHYFUR';
k(:,i) = 1.78e-13;
Gstr{i,1} = 'MOXYHYFUR';Gstr{i,2} = 'NO3';
fMOXYHYFUR(i)=fMOXYHYFUR(i)-1; fNO3(i)=fNO3(i)-1; fPPMOXYHYFUR(i)=fPPMOXYHYFUR(i)+1; 
 
 
i=i+1;
Rnames{i} = 'MPENTCN + NO3 = PPMPENTCN';
k(:,i) = 1e-18;
Gstr{i,1} = 'MPENTCN';Gstr{i,2} = 'NO3';
fMPENTCN(i)=fMPENTCN(i)-1; fNO3(i)=fNO3(i)-1; fPPMPENTCN(i)=fPPMPENTCN(i)+1; 
 
 
i=i+1;
Rnames{i} = 'MPHCOME + NO3 = PPMPHCOME';
k(:,i) = 6.85e-17;
Gstr{i,1} = 'MPHCOME';Gstr{i,2} = 'NO3';
fMPHCOME(i)=fMPHCOME(i)-1; fNO3(i)=fNO3(i)-1; fPPMPHCOME(i)=fPPMPHCOME(i)+1; 
 
 
i=i+1;
Rnames{i} = 'MPRK + NO3 = PPMPRK';
k(:,i) = 1e-15;
Gstr{i,1} = 'MPRK';Gstr{i,2} = 'NO3';
fMPRK(i)=fMPRK(i)-1; fNO3(i)=fNO3(i)-1; fPPMPRK(i)=fPPMPRK(i)+1; 
 
 
i=i+1;
Rnames{i} = 'MPROPBENZ + NO3 = PPMPROPBENZ';
k(:,i) = 1.51e-13;
Gstr{i,1} = 'MPROPBENZ';Gstr{i,2} = 'NO3';
fMPROPBENZ(i)=fMPROPBENZ(i)-1; fNO3(i)=fNO3(i)-1; fPPMPROPBENZ(i)=fPPMPROPBENZ(i)+1; 
 
 
i=i+1;
Rnames{i} = 'MPROPOATE + NO3 = PPMPROPOATE';
k(:,i) = 3.3e-17;
Gstr{i,1} = 'MPROPOATE';Gstr{i,2} = 'NO3';
fMPROPOATE(i)=fMPROPOATE(i)-1; fNO3(i)=fNO3(i)-1; fPPMPROPOATE(i)=fPPMPROPOATE(i)+1; 
 
 
i=i+1;
Rnames{i} = 'MPYRIDINE2 + NO3 = PPMPYRIDINE2';
k(:,i) = 4.8e-13;
Gstr{i,1} = 'MPYRIDINE2';Gstr{i,2} = 'NO3';
fMPYRIDINE2(i)=fMPYRIDINE2(i)-1; fNO3(i)=fNO3(i)-1; fPPMPYRIDINE2(i)=fPPMPYRIDINE2(i)+1; 
 
 
i=i+1;
Rnames{i} = 'MPYRIDINE3 + NO3 = PPMPYRIDINE3';
k(:,i) = 4.8e-13;
Gstr{i,1} = 'MPYRIDINE3';Gstr{i,2} = 'NO3';
fMPYRIDINE3(i)=fMPYRIDINE3(i)-1; fNO3(i)=fNO3(i)-1; fPPMPYRIDINE3(i)=fPPMPYRIDINE3(i)+1; 
 
 
i=i+1;
Rnames{i} = 'MPYRROLE + NO3 = PPMPYRROLE';
k(:,i) = 4.6e-11;
Gstr{i,1} = 'MPYRROLE';Gstr{i,2} = 'NO3';
fMPYRROLE(i)=fMPYRROLE(i)-1; fNO3(i)=fNO3(i)-1; fPPMPYRROLE(i)=fPPMPYRROLE(i)+1; 
 
 
i=i+1;
Rnames{i} = 'MSTYRENE + NO3 = PPMSTYRENE';
k(:,i) = 1.51e-12;
Gstr{i,1} = 'MSTYRENE';Gstr{i,2} = 'NO3';
fMSTYRENE(i)=fMSTYRENE(i)-1; fNO3(i)=fNO3(i)-1; fPPMSTYRENE(i)=fPPMSTYRENE(i)+1; 
 
 
i=i+1;
Rnames{i} = 'MTHIOL + NO3 = PPMTHIOL';
k(:,i) = 9.2e-13;
Gstr{i,1} = 'MTHIOL';Gstr{i,2} = 'NO3';
fMTHIOL(i)=fMTHIOL(i)-1; fNO3(i)=fNO3(i)-1; fPPMTHIOL(i)=fPPMTHIOL(i)+1; 
 
 
i=i+1;
Rnames{i} = 'MTHIOPHENE + NO3 = PPMTHIOPHENE';
k(:,i) = 9.6e-13;
Gstr{i,1} = 'MTHIOPHENE';Gstr{i,2} = 'NO3';
fMTHIOPHENE(i)=fMTHIOPHENE(i)-1; fNO3(i)=fNO3(i)-1; fPPMTHIOPHENE(i)=fPPMTHIOPHENE(i)+1; 
 
 
i=i+1;
Rnames{i} = 'MVK + NO3 = PPMVK';
k(:,i) = 1.2e-16;
Gstr{i,1} = 'MVK';Gstr{i,2} = 'NO3';
fMVK(i)=fMVK(i)-1; fNO3(i)=fNO3(i)-1; fPPMVK(i)=fPPMVK(i)+1; 
 
 
i=i+1;
Rnames{i} = 'MXYLCO2H + NO3 = PPMXYLCO2H';
k(:,i) = 1e-17;
Gstr{i,1} = 'MXYLCO2H';Gstr{i,2} = 'NO3';
fMXYLCO2H(i)=fMXYLCO2H(i)-1; fNO3(i)=fNO3(i)-1; fPPMXYLCO2H(i)=fPPMXYLCO2H(i)+1; 
 
 
i=i+1;
Rnames{i} = 'NAPT + NO3 = PPNAPT';
k(:,i) = 2e-11;
Gstr{i,1} = 'NAPT';Gstr{i,2} = 'NO3';
fNAPT(i)=fNAPT(i)-1; fNO3(i)=fNO3(i)-1; fPPNAPT(i)=fPPNAPT(i)+1; 
 
 
i=i+1;
Rnames{i} = 'NBUTACET + NO3 = PPNBUTACET';
k(:,i) = 5e-17;
Gstr{i,1} = 'NBUTACET';Gstr{i,2} = 'NO3';
fNBUTACET(i)=fNBUTACET(i)-1; fNO3(i)=fNO3(i)-1; fPPNBUTACET(i)=fPPNBUTACET(i)+1; 
 
 
i=i+1;
Rnames{i} = 'NBUTOL + NO3 = PPNBUTOL';
k(:,i) = 2.71e-15;
Gstr{i,1} = 'NBUTOL';Gstr{i,2} = 'NO3';
fNBUTOL(i)=fNBUTOL(i)-1; fNO3(i)=fNO3(i)-1; fPPNBUTOL(i)=fPPNBUTOL(i)+1; 
 
 
i=i+1;
Rnames{i} = 'NH3 + NO3 = PPNH3';
k(:,i) = 6e-16;
Gstr{i,1} = 'NH3';Gstr{i,2} = 'NO3';
fNH3(i)=fNH3(i)-1; fNO3(i)=fNO3(i)-1; fPPNH3(i)=fPPNH3(i)+1; 
 
 
i=i+1;
Rnames{i} = 'NON18DIEN + NO3 = PPNON18DIEN';
k(:,i) = 2.65e-14;
Gstr{i,1} = 'NON18DIEN';Gstr{i,2} = 'NO3';
fNON18DIEN(i)=fNON18DIEN(i)-1; fNO3(i)=fNO3(i)-1; fPPNON18DIEN(i)=fPPNON18DIEN(i)+1; 
 
 
i=i+1;
Rnames{i} = 'NONEN + NO3 = PPNONEN';
k(:,i) = 5.78e-13;
Gstr{i,1} = 'NONEN';Gstr{i,2} = 'NO3';
fNONEN(i)=fNONEN(i)-1; fNO3(i)=fNO3(i)-1; fPPNONEN(i)=fPPNONEN(i)+1; 
 
 
i=i+1;
Rnames{i} = 'NPROACET + NO3 = PPNPROACET';
k(:,i) = 1e-17;
Gstr{i,1} = 'NPROACET';Gstr{i,2} = 'NO3';
fNPROACET(i)=fNPROACET(i)-1; fNO3(i)=fNO3(i)-1; fPPNPROACET(i)=fPPNPROACET(i)+1; 
 
 
i=i+1;
Rnames{i} = 'OCT17DIEN + NO3 = PPOCT17DIEN';
k(:,i) = 2.63e-14;
Gstr{i,1} = 'OCT17DIEN';Gstr{i,2} = 'NO3';
fOCT17DIEN(i)=fOCT17DIEN(i)-1; fNO3(i)=fNO3(i)-1; fPPOCT17DIEN(i)=fPPOCT17DIEN(i)+1; 
 
 
i=i+1;
Rnames{i} = 'OCTENES + NO3 = PPOCTENES';
k(:,i) = 2.19e-14;
Gstr{i,1} = 'OCTENES';Gstr{i,2} = 'NO3';
fOCTENES(i)=fOCTENES(i)-1; fNO3(i)=fNO3(i)-1; fPPOCTENES(i)=fPPOCTENES(i)+1; 
 
 
i=i+1;
Rnames{i} = 'OTHFURAN + NO3 = PPOTHFURAN';
k(:,i) = 5.78e-11;
Gstr{i,1} = 'OTHFURAN';Gstr{i,2} = 'NO3';
fOTHFURAN(i)=fOTHFURAN(i)-1; fNO3(i)=fNO3(i)-1; fPPOTHFURAN(i)=fPPOTHFURAN(i)+1; 
 
 
i=i+1;
Rnames{i} = 'OTHMONOT + NO3 = PPOTHMONOT';
k(:,i) = 2.94e-11;
Gstr{i,1} = 'OTHMONOT';Gstr{i,2} = 'NO3';
fOTHMONOT(i)=fOTHMONOT(i)-1; fNO3(i)=fNO3(i)-1; fPPOTHMONOT(i)=fPPOTHMONOT(i)+1; 
 
 
i=i+1;
Rnames{i} = 'OXYFUR + NO3 = PPOXYFUR';
k(:,i) = 1.2e-12;
Gstr{i,1} = 'OXYFUR';Gstr{i,2} = 'NO3';
fOXYFUR(i)=fOXYFUR(i)-1; fNO3(i)=fNO3(i)-1; fPPOXYFUR(i)=fPPOXYFUR(i)+1; 
 
 
i=i+1;
Rnames{i} = 'OXYLCO2H + NO3 = PPOXYLCO2H';
k(:,i) = 1e-17;
Gstr{i,1} = 'OXYLCO2H';Gstr{i,2} = 'NO3';
fOXYLCO2H(i)=fOXYLCO2H(i)-1; fNO3(i)=fNO3(i)-1; fPPOXYLCO2H(i)=fPPOXYLCO2H(i)+1; 
 
 
i=i+1;
Rnames{i} = 'OXYMCYPENONE + NO3 = PPOXYMCYPENONE';
k(:,i) = 1.04e-12;
Gstr{i,1} = 'OXYMCYPENONE';Gstr{i,2} = 'NO3';
fOXYMCYPENONE(i)=fOXYMCYPENONE(i)-1; fNO3(i)=fNO3(i)-1; fPPOXYMCYPENONE(i)=fPPOXYMCYPENONE(i)+1; 
 
 
i=i+1;
Rnames{i} = 'OXYMFUR + NO3 = PPOXYMFUR';
k(:,i) = 1.2e-12;
Gstr{i,1} = 'OXYMFUR';Gstr{i,2} = 'NO3';
fOXYMFUR(i)=fOXYMFUR(i)-1; fNO3(i)=fNO3(i)-1; fPPOXYMFUR(i)=fPPOXYMFUR(i)+1; 
 
 
i=i+1;
Rnames{i} = 'OXYMFURONE + NO3 = PPOXYMFURONE';
k(:,i) = 1.76e-13;
Gstr{i,1} = 'OXYMFURONE';Gstr{i,2} = 'NO3';
fOXYMFURONE(i)=fOXYMFURONE(i)-1; fNO3(i)=fNO3(i)-1; fPPOXYMFURONE(i)=fPPOXYMFURONE(i)+1; 
 
 
i=i+1;
Rnames{i} = 'OXYMOHFURAN + NO3 = PPOXYMOHFURAN';
k(:,i) = 5.33e-14;
Gstr{i,1} = 'OXYMOHFURAN';Gstr{i,2} = 'NO3';
fOXYMOHFURAN(i)=fOXYMOHFURAN(i)-1; fNO3(i)=fNO3(i)-1; fPPOXYMOHFURAN(i)=fPPOXYMOHFURAN(i)+1; 
 
 
i=i+1;
Rnames{i} = 'OXYMONTS + NO3 = PPOXYMONTS';
k(:,i) = 3e-16;
Gstr{i,1} = 'OXYMONTS';Gstr{i,2} = 'NO3';
fOXYMONTS(i)=fOXYMONTS(i)-1; fNO3(i)=fNO3(i)-1; fPPOXYMONTS(i)=fPPOXYMONTS(i)+1; 
 
 
i=i+1;
Rnames{i} = 'OXYTETFUR + NO3 = PPOXYTETFUR';
k(:,i) = 1.18e-14;
Gstr{i,1} = 'OXYTETFUR';Gstr{i,2} = 'NO3';
fOXYTETFUR(i)=fOXYTETFUR(i)-1; fNO3(i)=fNO3(i)-1; fPPOXYTETFUR(i)=fPPOXYTETFUR(i)+1; 
 
 
i=i+1;
Rnames{i} = 'PENT14DIEN + NO3 = PPPENT14DIEN';
k(:,i) = 2.3e-14;
Gstr{i,1} = 'PENT14DIEN';Gstr{i,2} = 'NO3';
fPENT14DIEN(i)=fPENT14DIEN(i)-1; fNO3(i)=fNO3(i)-1; fPPPENT14DIEN(i)=fPPPENT14DIEN(i)+1; 
 
 
i=i+1;
Rnames{i} = 'PENT1EN1YN + NO3 = PPPENT1EN1YN';
k(:,i) = 6.9e-14;
Gstr{i,1} = 'PENT1EN1YN';Gstr{i,2} = 'NO3';
fPENT1EN1YN(i)=fPENT1EN1YN(i)-1; fNO3(i)=fNO3(i)-1; fPPPENT1EN1YN(i)=fPPPENT1EN1YN(i)+1; 
 
 
i=i+1;
Rnames{i} = 'PENT1YN + NO3 = PPPENT1YN';
k(:,i) = 5.45e-16;
Gstr{i,1} = 'PENT1YN';Gstr{i,2} = 'NO3';
fPENT1YN(i)=fPENT1YN(i)-1; fNO3(i)=fNO3(i)-1; fPPPENT1YN(i)=fPPPENT1YN(i)+1; 
 
 
i=i+1;
Rnames{i} = 'PENT4EN1YN + NO3 = PPPENT4EN1YN';
k(:,i) = 6.9e-14;
Gstr{i,1} = 'PENT4EN1YN';Gstr{i,2} = 'NO3';
fPENT4EN1YN(i)=fPENT4EN1YN(i)-1; fNO3(i)=fNO3(i)-1; fPPPENT4EN1YN(i)=fPPPENT4EN1YN(i)+1; 
 
 
i=i+1;
Rnames{i} = 'PENTANCN + NO3 = PPPENTANCN';
k(:,i) = 1e-18;
Gstr{i,1} = 'PENTANCN';Gstr{i,2} = 'NO3';
fPENTANCN(i)=fPENTANCN(i)-1; fNO3(i)=fNO3(i)-1; fPPPENTANCN(i)=fPPPENTANCN(i)+1; 
 
 
i=i+1;
Rnames{i} = 'PENTCN + NO3 = PPPENTCN';
k(:,i) = 6.86e-14;
Gstr{i,1} = 'PENTCN';Gstr{i,2} = 'NO3';
fPENTCN(i)=fPENTCN(i)-1; fNO3(i)=fNO3(i)-1; fPPPENTCN(i)=fPPPENTCN(i)+1; 
 
 
i=i+1;
Rnames{i} = 'PENTDENCN + NO3 = PPPENTDENCN';
k(:,i) = 2e-12;
Gstr{i,1} = 'PENTDENCN';Gstr{i,2} = 'NO3';
fPENTDENCN(i)=fPENTDENCN(i)-1; fNO3(i)=fNO3(i)-1; fPPPENTDENCN(i)=fPPPENTDENCN(i)+1; 
 
 
i=i+1;
Rnames{i} = 'PENTE13DIEN + NO3 = PPPENTE13DIEN';
k(:,i) = 2e-12;
Gstr{i,1} = 'PENTE13DIEN';Gstr{i,2} = 'NO3';
fPENTE13DIEN(i)=fPENTE13DIEN(i)-1; fNO3(i)=fNO3(i)-1; fPPPENTE13DIEN(i)=fPPPENTE13DIEN(i)+1; 
 
 
i=i+1;
Rnames{i} = 'PENTE2ENAL + NO3 = PPPENTE2ENAL';
k(:,i) = 8.79e-15;
Gstr{i,1} = 'PENTE2ENAL';Gstr{i,2} = 'NO3';
fPENTE2ENAL(i)=fPENTE2ENAL(i)-1; fNO3(i)=fNO3(i)-1; fPPPENTE2ENAL(i)=fPPPENTE2ENAL(i)+1; 
 
 
i=i+1;
Rnames{i} = 'PENTE3EN1YN + NO3 = PPPENTE3EN1YN';
k(:,i) = 6.9e-14;
Gstr{i,1} = 'PENTE3EN1YN';Gstr{i,2} = 'NO3';
fPENTE3EN1YN(i)=fPENTE3EN1YN(i)-1; fNO3(i)=fNO3(i)-1; fPPPENTE3EN1YN(i)=fPPPENTE3EN1YN(i)+1; 
 
 
i=i+1;
Rnames{i} = 'PENTEN4AL + NO3 = PPPENTEN4AL';
k(:,i) = 8.69e-15;
Gstr{i,1} = 'PENTEN4AL';Gstr{i,2} = 'NO3';
fPENTEN4AL(i)=fPENTEN4AL(i)-1; fNO3(i)=fNO3(i)-1; fPPPENTEN4AL(i)=fPPPENTEN4AL(i)+1; 
 
 
i=i+1;
Rnames{i} = 'PENTONE + NO3 = PPPENTONE';
k(:,i) = 5.63e-14;
Gstr{i,1} = 'PENTONE';Gstr{i,2} = 'NO3';
fPENTONE(i)=fPENTONE(i)-1; fNO3(i)=fNO3(i)-1; fPPPENTONE(i)=fPPPENTONE(i)+1; 
 
 
i=i+1;
Rnames{i} = 'PENTZ13DIEN + NO3 = PPPENTZ13DIEN';
k(:,i) = 2e-12;
Gstr{i,1} = 'PENTZ13DIEN';Gstr{i,2} = 'NO3';
fPENTZ13DIEN(i)=fPENTZ13DIEN(i)-1; fNO3(i)=fNO3(i)-1; fPPPENTZ13DIEN(i)=fPPPENTZ13DIEN(i)+1; 
 
 
i=i+1;
Rnames{i} = 'PENTZ3EN1YN + NO3 = PPPENTZ3EN1YN';
k(:,i) = 6.9e-14;
Gstr{i,1} = 'PENTZ3EN1YN';Gstr{i,2} = 'NO3';
fPENTZ3EN1YN(i)=fPENTZ3EN1YN(i)-1; fNO3(i)=fNO3(i)-1; fPPPENTZ3EN1YN(i)=fPPPENTZ3EN1YN(i)+1; 
 
 
i=i+1;
Rnames{i} = 'PHACETLY + NO3 = PPPHACETLY';
k(:,i) = 1e-16;
Gstr{i,1} = 'PHACETLY';Gstr{i,2} = 'NO3';
fPHACETLY(i)=fPHACETLY(i)-1; fNO3(i)=fNO3(i)-1; fPPPHACETLY(i)=fPPPHACETLY(i)+1; 
 
 
i=i+1;
Rnames{i} = 'PHCOME + NO3 = PPPHCOME';
k(:,i) = 3e-17;
Gstr{i,1} = 'PHCOME';Gstr{i,2} = 'NO3';
fPHCOME(i)=fPHCOME(i)-1; fNO3(i)=fNO3(i)-1; fPPPHCOME(i)=fPPPHCOME(i)+1; 
 
 
i=i+1;
Rnames{i} = 'PHEN4BUT3EN1YN + NO3 = PPPHEN4BUT3EN1YN';
k(:,i) = 1.25e-14;
Gstr{i,1} = 'PHEN4BUT3EN1YN';Gstr{i,2} = 'NO3';
fPHEN4BUT3EN1YN(i)=fPHEN4BUT3EN1YN(i)-1; fNO3(i)=fNO3(i)-1; fPPPHEN4BUT3EN1YN(i)=fPPPHEN4BUT3EN1YN(i)+1; 
 
 
i=i+1;
Rnames{i} = 'PROPANCN + NO3 = PPPROPANCN';
k(:,i) = 1e-18;
Gstr{i,1} = 'PROPANCN';Gstr{i,2} = 'NO3';
fPROPANCN(i)=fPROPANCN(i)-1; fNO3(i)=fNO3(i)-1; fPPPROPANCN(i)=fPPPROPANCN(i)+1; 
 
 
i=i+1;
Rnames{i} = 'PROPBENZ + NO3 = PPPROPBENZ';
k(:,i) = 2.29e-16;
Gstr{i,1} = 'PROPBENZ';Gstr{i,2} = 'NO3';
fPROPBENZ(i)=fPROPBENZ(i)-1; fNO3(i)=fNO3(i)-1; fPPPROPBENZ(i)=fPPPROPBENZ(i)+1; 
 
 
i=i+1;
Rnames{i} = 'PROPENNH3 + NO3 = PPPROPENNH3';
k(:,i) = 1.1e-12;
Gstr{i,1} = 'PROPENNH3';Gstr{i,2} = 'NO3';
fPROPENNH3(i)=fPROPENNH3(i)-1; fNO3(i)=fNO3(i)-1; fPPPROPENNH3(i)=fPPPROPENNH3(i)+1; 
 
 
i=i+1;
Rnames{i} = 'PROPYNAL + NO3 = PPPROPYNAL';
k(:,i) = 1.1e-14;
Gstr{i,1} = 'PROPYNAL';Gstr{i,2} = 'NO3';
fPROPYNAL(i)=fPROPYNAL(i)-1; fNO3(i)=fNO3(i)-1; fPPPROPYNAL(i)=fPPPROPYNAL(i)+1; 
 
 
i=i+1;
Rnames{i} = 'PROPYNBENZ + NO3 = PPPROPYNBENZ';
k(:,i) = 1.51e-12;
Gstr{i,1} = 'PROPYNBENZ';Gstr{i,2} = 'NO3';
fPROPYNBENZ(i)=fPROPYNBENZ(i)-1; fNO3(i)=fNO3(i)-1; fPPPROPYNBENZ(i)=fPPPROPYNBENZ(i)+1; 
 
 
i=i+1;
Rnames{i} = 'PROPYNCN + NO3 = PPPROPYNCN';
k(:,i) = 2.29e-16;
Gstr{i,1} = 'PROPYNCN';Gstr{i,2} = 'NO3';
fPROPYNCN(i)=fPROPYNCN(i)-1; fNO3(i)=fNO3(i)-1; fPPPROPYNCN(i)=fPPPROPYNCN(i)+1; 
 
 
i=i+1;
Rnames{i} = 'PXYLCO2H + NO3 = PPPXYLCO2H';
k(:,i) = 1e-17;
Gstr{i,1} = 'PXYLCO2H';Gstr{i,2} = 'NO3';
fPXYLCO2H(i)=fPXYLCO2H(i)-1; fNO3(i)=fNO3(i)-1; fPPPXYLCO2H(i)=fPPPXYLCO2H(i)+1; 
 
 
i=i+1;
Rnames{i} = 'PYRAL + NO3 = PPPYRAL';
k(:,i) = 4.8e-13;
Gstr{i,1} = 'PYRAL';Gstr{i,2} = 'NO3';
fPYRAL(i)=fPYRAL(i)-1; fNO3(i)=fNO3(i)-1; fPPPYRAL(i)=fPPPYRAL(i)+1; 
 
 
i=i+1;
Rnames{i} = 'PYRIDINE + NO3 = PPPYRIDINE';
k(:,i) = 4.8e-13;
Gstr{i,1} = 'PYRIDINE';Gstr{i,2} = 'NO3';
fPYRIDINE(i)=fPYRIDINE(i)-1; fNO3(i)=fNO3(i)-1; fPPPYRIDINE(i)=fPPPYRIDINE(i)+1; 
 
 
i=i+1;
Rnames{i} = 'PYRIDINOL + NO3 = PPPYRIDINOL';
k(:,i) = 4.8e-13;
Gstr{i,1} = 'PYRIDINOL';Gstr{i,2} = 'NO3';
fPYRIDINOL(i)=fPYRIDINOL(i)-1; fNO3(i)=fNO3(i)-1; fPPPYRIDINOL(i)=fPPPYRIDINOL(i)+1; 
 
 
i=i+1;
Rnames{i} = 'PYRROLE + NO3 = PPPYRROLE';
k(:,i) = 4.6e-11;
Gstr{i,1} = 'PYRROLE';Gstr{i,2} = 'NO3';
fPYRROLE(i)=fPYRROLE(i)-1; fNO3(i)=fNO3(i)-1; fPPPYRROLE(i)=fPPPYRROLE(i)+1; 
 
 
i=i+1;
Rnames{i} = 'SABINENE + NO3 = PPSABINENE';
k(:,i) = 1e-11;
Gstr{i,1} = 'SABINENE';Gstr{i,2} = 'NO3';
fSABINENE(i)=fSABINENE(i)-1; fNO3(i)=fNO3(i)-1; fPPSABINENE(i)=fPPSABINENE(i)+1; 
 
 
i=i+1;
Rnames{i} = 'SALAL + NO3 = PPSALAL';
k(:,i) = 3.64e-12;
Gstr{i,1} = 'SALAL';Gstr{i,2} = 'NO3';
fSALAL(i)=fSALAL(i)-1; fNO3(i)=fNO3(i)-1; fPPSALAL(i)=fPPSALAL(i)+1; 
 
 
i=i+1;
Rnames{i} = 'TERPINOLENE + NO3 = PPTERPINOLENE';
k(:,i) = 9.7e-11;
Gstr{i,1} = 'TERPINOLENE';Gstr{i,2} = 'NO3';
fTERPINOLENE(i)=fTERPINOLENE(i)-1; fNO3(i)=fNO3(i)-1; fPPTERPINOLENE(i)=fPPTERPINOLENE(i)+1; 
 
 
i=i+1;
Rnames{i} = 'TETMBENZ + NO3 = PPTETMBENZ';
k(:,i) = 1.9e-15;
Gstr{i,1} = 'TETMBENZ';Gstr{i,2} = 'NO3';
fTETMBENZ(i)=fTETMBENZ(i)-1; fNO3(i)=fNO3(i)-1; fPPTETMBENZ(i)=fPPTETMBENZ(i)+1; 
 
 
i=i+1;
Rnames{i} = 'TETRADECEN + NO3 = PPTETRADECEN';
k(:,i) = 2.42e-14;
Gstr{i,1} = 'TETRADECEN';Gstr{i,2} = 'NO3';
fTETRADECEN(i)=fTETRADECEN(i)-1; fNO3(i)=fNO3(i)-1; fPPTETRADECEN(i)=fPPTETRADECEN(i)+1; 
 
 
i=i+1;
Rnames{i} = 'THIOPHENE + NO3 = PPTHIOPHENE';
k(:,i) = 3.94e-14;
Gstr{i,1} = 'THIOPHENE';Gstr{i,2} = 'NO3';
fTHIOPHENE(i)=fTHIOPHENE(i)-1; fNO3(i)=fNO3(i)-1; fPPTHIOPHENE(i)=fPPTHIOPHENE(i)+1; 
 
 
i=i+1;
Rnames{i} = 'TMNH3 + NO3 = PPTMNH3';
k(:,i) = 5e-13;
Gstr{i,1} = 'TMNH3';Gstr{i,2} = 'NO3';
fTMNH3(i)=fTMNH3(i)-1; fNO3(i)=fNO3(i)-1; fPPTMNH3(i)=fPPTMNH3(i)+1; 
 
 
i=i+1;
Rnames{i} = 'TOLNO2 + NO3 = PPTOLNO2';
k(:,i) = 6.79e-17;
Gstr{i,1} = 'TOLNO2';Gstr{i,2} = 'NO3';
fTOLNO2(i)=fTOLNO2(i)-1; fNO3(i)=fNO3(i)-1; fPPTOLNO2(i)=fPPTOLNO2(i)+1; 
 
 
i=i+1;
Rnames{i} = 'TOLUENE + NO3 = PPTOLUENE';
k(:,i) = 6.79e-17;
Gstr{i,1} = 'TOLUENE';Gstr{i,2} = 'NO3';
fTOLUENE(i)=fTOLUENE(i)-1; fNO3(i)=fNO3(i)-1; fPPTOLUENE(i)=fPPTOLUENE(i)+1; 
 
 
i=i+1;
Rnames{i} = 'TRIDECEN + NO3 = PPTRIDECEN';
k(:,i) = 2.33e-14;
Gstr{i,1} = 'TRIDECEN';Gstr{i,2} = 'NO3';
fTRIDECEN(i)=fTRIDECEN(i)-1; fNO3(i)=fNO3(i)-1; fPPTRIDECEN(i)=fPPTRIDECEN(i)+1; 
 
 
i=i+1;
Rnames{i} = 'UNDEC110DIEN + NO3 = PPUNDEC110DIEN';
k(:,i) = 3.5e-14;
Gstr{i,1} = 'UNDEC110DIEN';Gstr{i,2} = 'NO3';
fUNDEC110DIEN(i)=fUNDEC110DIEN(i)-1; fNO3(i)=fNO3(i)-1; fPPUNDEC110DIEN(i)=fPPUNDEC110DIEN(i)+1; 
 
 
i=i+1;
Rnames{i} = 'UNDECEN + NO3 = PPUNDECEN';
k(:,i) = 2.1e-14;
Gstr{i,1} = 'UNDECEN';Gstr{i,2} = 'NO3';
fUNDECEN(i)=fUNDECEN(i)-1; fNO3(i)=fNO3(i)-1; fPPUNDECEN(i)=fPPUNDECEN(i)+1; 
 
 
i=i+1;
Rnames{i} = 'VANILIN + NO3 = PPVANILIN';
k(:,i) = 2.69e-11;
Gstr{i,1} = 'VANILIN';Gstr{i,2} = 'NO3';
fVANILIN(i)=fVANILIN(i)-1; fNO3(i)=fNO3(i)-1; fPPVANILIN(i)=fPPVANILIN(i)+1; 
 
 
i=i+1;
Rnames{i} = 'VFURAN + NO3 = PPVFURAN';
k(:,i) = 1.3e-11;
Gstr{i,1} = 'VFURAN';Gstr{i,2} = 'NO3';
fVFURAN(i)=fVFURAN(i)-1; fNO3(i)=fNO3(i)-1; fPPVFURAN(i)=fPPVFURAN(i)+1; 
 
 
i=i+1;
Rnames{i} = 'VGUAIACOL + NO3 = PPVGUAIACOL';
k(:,i) = 2.69e-11;
Gstr{i,1} = 'VGUAIACOL';Gstr{i,2} = 'NO3';
fVGUAIACOL(i)=fVGUAIACOL(i)-1; fNO3(i)=fNO3(i)-1; fPPVGUAIACOL(i)=fPPVGUAIACOL(i)+1; 
 
 
i=i+1;
Rnames{i} = 'VINLYLPYR + NO3 = PPVINLYLPYR';
k(:,i) = 4.8e-13;
Gstr{i,1} = 'VINLYLPYR';Gstr{i,2} = 'NO3';
fVINLYLPYR(i)=fVINLYLPYR(i)-1; fNO3(i)=fNO3(i)-1; fPPVINLYLPYR(i)=fPPVINLYLPYR(i)+1; 
 
 
i=i+1;
Rnames{i} = 'PENT2ENE + NO3 = PPPENT2ENE';
k(:,i) = 3.78e-13;
Gstr{i,1} = 'PENT2ENE';Gstr{i,2} = 'NO3';
fPENT2ENE(i)=fPENT2ENE(i)-1; fNO3(i)=fNO3(i)-1; fPPPENT2ENE(i)=fPPPENT2ENE(i)+1; 
 
 
i=i+1;
Rnames{i} = 'GUAIACOL + NO3 = NR1GUAIACOL';
k(:,i) = 0.5.*2.69e-11;
Gstr{i,1} = 'GUAIACOL';Gstr{i,2} = 'NO3';
fGUAIACOL(i)=fGUAIACOL(i)-1; fNO3(i)=fNO3(i)-1; fNR1GUAIACOL(i)=fNR1GUAIACOL(i)+1; 
 
 
i=i+1;
Rnames{i} = 'NR1GUAIACOL + NO2 = NR12GUAIACOL';
k(:,i) = 1e-10;
Gstr{i,1} = 'NR1GUAIACOL';Gstr{i,2} = 'NO2';
fNR1GUAIACOL(i)=fNR1GUAIACOL(i)-1; fNO2(i)=fNO2(i)-1; fNR12GUAIACOL(i)=fNR12GUAIACOL(i)+1; 
 
 
i=i+1;
Rnames{i} = 'NR12GUAIACOL = HNO3 + N6GUAIACOL';
k(:,i) = 1;
Gstr{i,1} = 'NR12GUAIACOL';
fNR12GUAIACOL(i)=fNR12GUAIACOL(i)-1; fHNO3(i)=fHNO3(i)+1; fN6GUAIACOL(i)=fN6GUAIACOL(i)+1; 
 
 
i=i+1;
Rnames{i} = 'NR1GUAIACOL + NO2 = NR14GUAIACOL';
k(:,i) = 1e-10;
Gstr{i,1} = 'NR1GUAIACOL';Gstr{i,2} = 'NO2';
fNR1GUAIACOL(i)=fNR1GUAIACOL(i)-1; fNO2(i)=fNO2(i)-1; fNR14GUAIACOL(i)=fNR14GUAIACOL(i)+1; 
 
 
i=i+1;
Rnames{i} = 'NR14GUAIACOL = HNO3 + N4GUAIACOL';
k(:,i) = 1;
Gstr{i,1} = 'NR14GUAIACOL';
fNR14GUAIACOL(i)=fNR14GUAIACOL(i)-1; fHNO3(i)=fHNO3(i)+1; fN4GUAIACOL(i)=fN4GUAIACOL(i)+1; 
 
 
i=i+1;
Rnames{i} = 'MGUAIACOL + NO3 = NR5MGUAIACOL';
k(:,i) = 8.41e-11;
Gstr{i,1} = 'MGUAIACOL';Gstr{i,2} = 'NO3';
fMGUAIACOL(i)=fMGUAIACOL(i)-1; fNO3(i)=fNO3(i)-1; fNR5MGUAIACOL(i)=fNR5MGUAIACOL(i)+1; 
 
 
i=i+1;
Rnames{i} = 'NR5MGUAIACOL + NO2 = NR56MGUAIACOL';
k(:,i) = 1e-10;
Gstr{i,1} = 'NR5MGUAIACOL';Gstr{i,2} = 'NO2';
fNR5MGUAIACOL(i)=fNR5MGUAIACOL(i)-1; fNO2(i)=fNO2(i)-1; fNR56MGUAIACOL(i)=fNR56MGUAIACOL(i)+1; 
 
 
i=i+1;
Rnames{i} = 'NR56MGUAIACOL = HNO3 + N6MGUAIACOL';
k(:,i) = 1;
Gstr{i,1} = 'NR56MGUAIACOL';
fNR56MGUAIACOL(i)=fNR56MGUAIACOL(i)-1; fHNO3(i)=fHNO3(i)+1; fN6MGUAIACOL(i)=fN6MGUAIACOL(i)+1; 
 
 
i=i+1;
Rnames{i} = 'SYRINGOL + NO3 = NR4SYRINGOL';
k(:,i) = 1.58e-10;
Gstr{i,1} = 'SYRINGOL';Gstr{i,2} = 'NO3';
fSYRINGOL(i)=fSYRINGOL(i)-1; fNO3(i)=fNO3(i)-1; fNR4SYRINGOL(i)=fNR4SYRINGOL(i)+1; 
 
 
i=i+1;
Rnames{i} = 'NR4SYRINGOL + NO2 = NR34SYRINGOL';
k(:,i) = 1e-10;
Gstr{i,1} = 'NR4SYRINGOL';Gstr{i,2} = 'NO2';
fNR4SYRINGOL(i)=fNR4SYRINGOL(i)-1; fNO2(i)=fNO2(i)-1; fNR34SYRINGOL(i)=fNR34SYRINGOL(i)+1; 
 
 
i=i+1;
Rnames{i} = 'NR34SYRINGOL = HNO3 + N3SYRINGOL';
k(:,i) = 1;
Gstr{i,1} = 'NR34SYRINGOL';
fNR34SYRINGOL(i)=fNR34SYRINGOL(i)-1; fHNO3(i)=fHNO3(i)+1; fN3SYRINGOL(i)=fN3SYRINGOL(i)+1; 
 
 
i=i+1;
Rnames{i} = 'N2O5 + AeroSA = HNO3 + AeroSA';
k(:,i) = 0.5.*0.038.*(T.^0.5);
Gstr{i,1} = 'N2O5';Gstr{i,2} = 'AeroSA';
fN2O5(i)=fN2O5(i)-1; fAeroSA(i)=fAeroSA(i)-1; fHNO3(i)=fHNO3(i)+1; fAeroSA(i)=fAeroSA(i)+1; 
 
 
i=i+1;
Rnames{i} = 'N2O5 + AeroSA = ClNO2 + AeroSA';
k(:,i) = 0.5.*0.038.*(T.^0.5);
Gstr{i,1} = 'N2O5';Gstr{i,2} = 'AeroSA';
fN2O5(i)=fN2O5(i)-1; fAeroSA(i)=fAeroSA(i)-1; fClNO2(i)=fClNO2(i)+1; fAeroSA(i)=fAeroSA(i)+1; 
 
 
i=i+1;
Rnames{i} = 'C4MDIAL = MMALANHY';
k(:,i) = 0.9288.*1e-10;
Gstr{i,1} = 'C4MDIAL';
fC4MDIAL(i)=fC4MDIAL(i)-1; fMMALANHY(i)=fMMALANHY(i)+1; 
 
 
i=i+1;
Rnames{i} = 'NO3 + AeroSA = AeroNO3 + AeroSA';
k(:,i) = 0.005014*(T.^0.5);
Gstr{i,1} = 'NO3';Gstr{i,2} = 'AeroSA';
fNO3(i)=fNO3(i)-1; fAeroSA(i)=fAeroSA(i)-1; fAeroNO3(i)=fAeroNO3(i)+1; fAeroSA(i)=fAeroSA(i)+1; 
 
 
i=i+1;
Rnames{i} = 'C5H6 + O3 = PO3C5H6';
k(:,i) = 3.14E-15;
Gstr{i,1} = 'C5H6';Gstr{i,2} = 'O3';
fC5H6(i)=fC5H6(i)-1; fO3(i)=fO3(i)-1; fPO3C5H6(i)=fPO3C5H6(i)+1; 
 
 
i=i+1;
Rnames{i} = 'M1CYPENT13DIEN + O3 = PO3M1CYPENT13DIEN';
k(:,i) = 3.14E-15;
Gstr{i,1} = 'M1CYPENT13DIEN';Gstr{i,2} = 'O3';
fM1CYPENT13DIEN(i)=fM1CYPENT13DIEN(i)-1; fO3(i)=fO3(i)-1; fPO3M1CYPENT13DIEN(i)=fPO3M1CYPENT13DIEN(i)+1; 
 
 
i=i+1;
Rnames{i} = 'M5CYPENT13DIEN + O3 = PO3M5CYPENT13DIEN';
k(:,i) = 3.14E-15;
Gstr{i,1} = 'M5CYPENT13DIEN';Gstr{i,2} = 'O3';
fM5CYPENT13DIEN(i)=fM5CYPENT13DIEN(i)-1; fO3(i)=fO3(i)-1; fPO3M5CYPENT13DIEN(i)=fPO3M5CYPENT13DIEN(i)+1; 
 
 
i=i+1;
Rnames{i} = 'APHELLANDRENE + O3 = PO3APHELLANDRENE';
k(:,i) = 3.00E-15;
Gstr{i,1} = 'APHELLANDRENE';Gstr{i,2} = 'O3';
fAPHELLANDRENE(i)=fAPHELLANDRENE(i)-1; fO3(i)=fO3(i)-1; fPO3APHELLANDRENE(i)=fPO3APHELLANDRENE(i)+1; 
 
 
i=i+1;
Rnames{i} = 'OTHMONOT + O3 = PO3OTHMONOT';
k(:,i) = 1.94E-15;
Gstr{i,1} = 'OTHMONOT';Gstr{i,2} = 'O3';
fOTHMONOT(i)=fOTHMONOT(i)-1; fO3(i)=fO3(i)-1; fPO3OTHMONOT(i)=fPO3OTHMONOT(i)+1; 
 
 
i=i+1;
Rnames{i} = 'TERPINOLENE + O3 = PO3TERPINOLENE';
k(:,i) = 1.60E-15;
Gstr{i,1} = 'TERPINOLENE';Gstr{i,2} = 'O3';
fTERPINOLENE(i)=fTERPINOLENE(i)-1; fO3(i)=fO3(i)-1; fPO3TERPINOLENE(i)=fPO3TERPINOLENE(i)+1; 
 
 
i=i+1;
Rnames{i} = 'CYHEX13DIEN + O3 = PO3CYHEX13DIEN';
k(:,i) = 1.22E-15;
Gstr{i,1} = 'CYHEX13DIEN';Gstr{i,2} = 'O3';
fCYHEX13DIEN(i)=fCYHEX13DIEN(i)-1; fO3(i)=fO3(i)-1; fPO3CYHEX13DIEN(i)=fPO3CYHEX13DIEN(i)+1; 
 
 
i=i+1;
Rnames{i} = 'EZOCIMENE + O3 = PO3EZOCIMENE';
k(:,i) = 4.90E-16;
Gstr{i,1} = 'EZOCIMENE';Gstr{i,2} = 'O3';
fEZOCIMENE(i)=fEZOCIMENE(i)-1; fO3(i)=fO3(i)-1; fPO3EZOCIMENE(i)=fPO3EZOCIMENE(i)+1; 
 
 
i=i+1;
Rnames{i} = 'BMYRCENE + O3 = PO3BMYRCENE';
k(:,i) = 4.60E-16;
Gstr{i,1} = 'BMYRCENE';Gstr{i,2} = 'O3';
fBMYRCENE(i)=fBMYRCENE(i)-1; fO3(i)=fO3(i)-1; fPO3BMYRCENE(i)=fPO3BMYRCENE(i)+1; 
 
 
i=i+1;
Rnames{i} = 'M1CYPENEN + O3 = PO3M1CYPENEN';
k(:,i) = 4.54E-16;
Gstr{i,1} = 'M1CYPENEN';Gstr{i,2} = 'O3';
fM1CYPENEN(i)=fM1CYPENEN(i)-1; fO3(i)=fO3(i)-1; fPO3M1CYPENEN(i)=fPO3M1CYPENEN(i)+1; 
 
 
i=i+1;
Rnames{i} = 'M2PENT2EN + O3 = PO3M2PENT2EN';
k(:,i) = 4.54E-16;
Gstr{i,1} = 'M2PENT2EN';Gstr{i,2} = 'O3';
fM2PENT2EN(i)=fM2PENT2EN(i)-1; fO3(i)=fO3(i)-1; fPO3M2PENT2EN(i)=fPO3M2PENT2EN(i)+1; 
 
 
i=i+1;
Rnames{i} = 'C3FURANS + O3 = PO3C3FURANS';
k(:,i) = 4.20E-16;
Gstr{i,1} = 'C3FURANS';Gstr{i,2} = 'O3';
fC3FURANS(i)=fC3FURANS(i)-1; fO3(i)=fO3(i)-1; fPO3C3FURANS(i)=fPO3C3FURANS(i)+1; 
 
 
i=i+1;
Rnames{i} = 'DIHYMFUR + O3 = PO3DIHYMFUR';
k(:,i) = 4.20E-16;
Gstr{i,1} = 'DIHYMFUR';Gstr{i,2} = 'O3';
fDIHYMFUR(i)=fDIHYMFUR(i)-1; fO3(i)=fO3(i)-1; fPO3DIHYMFUR(i)=fPO3DIHYMFUR(i)+1; 
 
 
i=i+1;
Rnames{i} = 'DIMEFURAN + O3 = PO3DIMEFURAN';
k(:,i) = 4.20E-16;
Gstr{i,1} = 'DIMEFURAN';Gstr{i,2} = 'O3';
fDIMEFURAN(i)=fDIMEFURAN(i)-1; fO3(i)=fO3(i)-1; fPO3DIMEFURAN(i)=fPO3DIMEFURAN(i)+1; 
 
 
i=i+1;
Rnames{i} = 'OTHFURAN + O3 = PO3OTHFURAN';
k(:,i) = 4.20E-16;
Gstr{i,1} = 'OTHFURAN';Gstr{i,2} = 'O3';
fOTHFURAN(i)=fOTHFURAN(i)-1; fO3(i)=fO3(i)-1; fPO3OTHFURAN(i)=fPO3OTHFURAN(i)+1; 
 
 
i=i+1;
Rnames{i} = 'M3CYHEXEN + O3 = PO3M3CYHEXEN';
k(:,i) = 1.53E-16;
Gstr{i,1} = 'M3CYHEXEN';Gstr{i,2} = 'O3';
fM3CYHEXEN(i)=fM3CYHEXEN(i)-1; fO3(i)=fO3(i)-1; fPO3M3CYHEXEN(i)=fPO3M3CYHEXEN(i)+1; 
 
 
i=i+1;
Rnames{i} = 'INDENE + O3 = PO3INDENE';
k(:,i) = 1.50E-16;
Gstr{i,1} = 'INDENE';Gstr{i,2} = 'O3';
fINDENE(i)=fINDENE(i)-1; fO3(i)=fO3(i)-1; fPO3INDENE(i)=fPO3INDENE(i)+1; 
 
 
i=i+1;
Rnames{i} = 'M2PENTZ13DIEN + O3 = PO3M2PENTZ13DIEN';
k(:,i) = 8.00E-17;
Gstr{i,1} = 'M2PENTZ13DIEN';Gstr{i,2} = 'O3';
fM2PENTZ13DIEN(i)=fM2PENTZ13DIEN(i)-1; fO3(i)=fO3(i)-1; fPO3M2PENTZ13DIEN(i)=fPO3M2PENTZ13DIEN(i)+1; 
 
 
i=i+1;
Rnames{i} = 'BPHELLANDRENE + O3 = PO3BPHELLANDRENE';
k(:,i) = 5.00E-17;
Gstr{i,1} = 'BPHELLANDRENE';Gstr{i,2} = 'O3';
fBPHELLANDRENE(i)=fBPHELLANDRENE(i)-1; fO3(i)=fO3(i)-1; fPO3BPHELLANDRENE(i)=fPO3BPHELLANDRENE(i)+1; 
 
 
i=i+1;
Rnames{i} = 'CARENE3 + O3 = PO3CARENE3';
k(:,i) = 4.80E-17;
Gstr{i,1} = 'CARENE3';Gstr{i,2} = 'O3';
fCARENE3(i)=fCARENE3(i)-1; fO3(i)=fO3(i)-1; fPO3CARENE3(i)=fPO3CARENE3(i)+1; 
 
 
i=i+1;
Rnames{i} = 'PENTE13DIEN + O3 = PO3PENTE13DIEN';
k(:,i) = 4.31E-17;
Gstr{i,1} = 'PENTE13DIEN';Gstr{i,2} = 'O3';
fPENTE13DIEN(i)=fPENTE13DIEN(i)-1; fO3(i)=fO3(i)-1; fPO3PENTE13DIEN(i)=fPO3PENTE13DIEN(i)+1; 
 
 
i=i+1;
Rnames{i} = 'PENTZ13DIEN + O3 = PO3PENTZ13DIEN';
k(:,i) = 2.78E-17;
Gstr{i,1} = 'PENTZ13DIEN';Gstr{i,2} = 'O3';
fPENTZ13DIEN(i)=fPENTZ13DIEN(i)-1; fO3(i)=fO3(i)-1; fPO3PENTZ13DIEN(i)=fPO3PENTZ13DIEN(i)+1; 
 
 
i=i+1;
Rnames{i} = 'ETHFURAN2 + O3 = PO3ETHFURAN2';
k(:,i) = 2.05E-17;
Gstr{i,1} = 'ETHFURAN2';Gstr{i,2} = 'O3';
fETHFURAN2(i)=fETHFURAN2(i)-1; fO3(i)=fO3(i)-1; fPO3ETHFURAN2(i)=fPO3ETHFURAN2(i)+1; 
 
 
i=i+1;
Rnames{i} = 'M2FURAN + O3 = PO3M2FURAN';
k(:,i) = 2.05E-17;
Gstr{i,1} = 'M2FURAN';Gstr{i,2} = 'O3';
fM2FURAN(i)=fM2FURAN(i)-1; fO3(i)=fO3(i)-1; fPO3M2FURAN(i)=fPO3M2FURAN(i)+1; 
 
 
i=i+1;
Rnames{i} = 'M2OLFURAN + O3 = PO3M2OLFURAN';
k(:,i) = 2.05E-17;
Gstr{i,1} = 'M2OLFURAN';Gstr{i,2} = 'O3';
fM2OLFURAN(i)=fM2OLFURAN(i)-1; fO3(i)=fO3(i)-1; fPO3M2OLFURAN(i)=fPO3M2OLFURAN(i)+1; 
 
 
i=i+1;
Rnames{i} = 'MEFURFURAL + O3 = PO3MEFURFURAL';
k(:,i) = 2.05E-17;
Gstr{i,1} = 'MEFURFURAL';Gstr{i,2} = 'O3';
fMEFURFURAL(i)=fMEFURFURAL(i)-1; fO3(i)=fO3(i)-1; fPO3MEFURFURAL(i)=fPO3MEFURFURAL(i)+1; 
 
 
i=i+1;
Rnames{i} = 'FURAN23DIHYD + O3 = PO3FURAN23DIHYD';
k(:,i) = 1.61E-17;
Gstr{i,1} = 'FURAN23DIHYD';Gstr{i,2} = 'O3';
fFURAN23DIHYD(i)=fFURAN23DIHYD(i)-1; fO3(i)=fO3(i)-1; fPO3FURAN23DIHYD(i)=fPO3FURAN23DIHYD(i)+1; 
 
 
i=i+1;
Rnames{i} = 'M5FURAN23DIHY + O3 = PO3M5FURAN23DIHY';
k(:,i) = 1.61E-17;
Gstr{i,1} = 'M5FURAN23DIHY';Gstr{i,2} = 'O3';
fM5FURAN23DIHY(i)=fM5FURAN23DIHY(i)-1; fO3(i)=fO3(i)-1; fPO3M5FURAN23DIHY(i)=fPO3M5FURAN23DIHY(i)+1; 
 
 
i=i+1;
Rnames{i} = 'C3PYRROLE + O3 = PO3C3PYRROLE';
k(:,i) = 1.57E-17;
Gstr{i,1} = 'C3PYRROLE';Gstr{i,2} = 'O3';
fC3PYRROLE(i)=fC3PYRROLE(i)-1; fO3(i)=fO3(i)-1; fPO3C3PYRROLE(i)=fPO3C3PYRROLE(i)+1; 
 
 
i=i+1;
Rnames{i} = 'DHYPYRROLE + O3 = PO3DHYPYRROLE';
k(:,i) = 1.57E-17;
Gstr{i,1} = 'DHYPYRROLE';Gstr{i,2} = 'O3';
fDHYPYRROLE(i)=fDHYPYRROLE(i)-1; fO3(i)=fO3(i)-1; fPO3DHYPYRROLE(i)=fPO3DHYPYRROLE(i)+1; 
 
 
i=i+1;
Rnames{i} = 'DIMPYRROLE + O3 = PO3DIMPYRROLE';
k(:,i) = 1.57E-17;
Gstr{i,1} = 'DIMPYRROLE';Gstr{i,2} = 'O3';
fDIMPYRROLE(i)=fDIMPYRROLE(i)-1; fO3(i)=fO3(i)-1; fPO3DIMPYRROLE(i)=fPO3DIMPYRROLE(i)+1; 
 
 
i=i+1;
Rnames{i} = 'ETPYRROLE + O3 = PO3ETPYRROLE';
k(:,i) = 1.57E-17;
Gstr{i,1} = 'ETPYRROLE';Gstr{i,2} = 'O3';
fETPYRROLE(i)=fETPYRROLE(i)-1; fO3(i)=fO3(i)-1; fPO3ETPYRROLE(i)=fPO3ETPYRROLE(i)+1; 
 
 
i=i+1;
Rnames{i} = 'MPYRROLE + O3 = PO3MPYRROLE';
k(:,i) = 1.57E-17;
Gstr{i,1} = 'MPYRROLE';Gstr{i,2} = 'O3';
fMPYRROLE(i)=fMPYRROLE(i)-1; fO3(i)=fO3(i)-1; fPO3MPYRROLE(i)=fPO3MPYRROLE(i)+1; 
 
 
i=i+1;
Rnames{i} = 'PYRROLE + O3 = PO3PYRROLE';
k(:,i) = 1.57E-17;
Gstr{i,1} = 'PYRROLE';Gstr{i,2} = 'O3';
fPYRROLE(i)=fPYRROLE(i)-1; fO3(i)=fO3(i)-1; fPO3PYRROLE(i)=fPO3PYRROLE(i)+1; 
 
 
i=i+1;
Rnames{i} = 'FURAN25DIHYD + O3 = PO3FURAN25DIHYD';
k(:,i) = 3.22E-18;
Gstr{i,1} = 'FURAN25DIHYD';Gstr{i,2} = 'O3';
fFURAN25DIHYD(i)=fFURAN25DIHYD(i)-1; fO3(i)=fO3(i)-1; fPO3FURAN25DIHYD(i)=fPO3FURAN25DIHYD(i)+1; 
 
 
i=i+1;
Rnames{i} = 'FURAN + O3 = PO3FURAN';
%k(:,i) = 2.60E-18;
k(:,i) = 2.40E-18;
Gstr{i,1} = 'FURAN';Gstr{i,2} = 'O3';
fFURAN(i)=fFURAN(i)-1; fO3(i)=fO3(i)-1; fPO3FURAN(i)=fPO3FURAN(i)+1; 
 
 
i=i+1;
Rnames{i} = 'FURFURAL + O3 = PO3FURFURAL';
k(:,i) = 2.60E-18;
Gstr{i,1} = 'FURFURAL';Gstr{i,2} = 'O3';
fFURFURAL(i)=fFURFURAL(i)-1; fO3(i)=fO3(i)-1; fPO3FURFURAL(i)=fPO3FURFURAL(i)+1; 
 
 
i=i+1;
Rnames{i} = 'FURFURAL3 + O3 = PO3FURFURAL3';
k(:,i) = 2.60E-18;
Gstr{i,1} = 'FURFURAL3';Gstr{i,2} = 'O3';
fFURFURAL3(i)=fFURFURAL3(i)-1; fO3(i)=fO3(i)-1; fPO3FURFURAL3(i)=fPO3FURFURAL3(i)+1; 
 
 
i=i+1;
Rnames{i} = 'OXYFUR + O3 = PO3OXYFUR';
k(:,i) = 2.60E-18;
Gstr{i,1} = 'OXYFUR';Gstr{i,2} = 'O3';
fOXYFUR(i)=fOXYFUR(i)-1; fO3(i)=fO3(i)-1; fPO3OXYFUR(i)=fPO3OXYFUR(i)+1; 
 
 
i=i+1;
Rnames{i} = 'OXYMFUR + O3 = PO3OXYMFUR';
k(:,i) = 2.60E-18;
Gstr{i,1} = 'OXYMFUR';Gstr{i,2} = 'O3';
fOXYMFUR(i)=fOXYMFUR(i)-1; fO3(i)=fO3(i)-1; fPO3OXYMFUR(i)=fPO3OXYMFUR(i)+1; 
 
 
i=i+1;
Rnames{i} = 'OXYMCYPENONE + O3 = PO3OXYMCYPENONE';
k(:,i) = 1.22E-18;
Gstr{i,1} = 'OXYMCYPENONE';Gstr{i,2} = 'O3';
fOXYMCYPENONE(i)=fOXYMCYPENONE(i)-1; fO3(i)=fO3(i)-1; fPO3OXYMCYPENONE(i)=fPO3OXYMCYPENONE(i)+1; 
 
 
i=i+1;
Rnames{i} = 'DIMNAP + O3 = PO3DIMNAP';
k(:,i) = 4.00E-19;
Gstr{i,1} = 'DIMNAP';Gstr{i,2} = 'O3';
fDIMNAP(i)=fDIMNAP(i)-1; fO3(i)=fO3(i)-1; fPO3DIMNAP(i)=fPO3DIMNAP(i)+1; 
 
 
i=i+1;
Rnames{i} = 'GUAIACOL + O3 = PO3GUAIACOL';
k(:,i) = 4.00E-19;
Gstr{i,1} = 'GUAIACOL';Gstr{i,2} = 'O3';
fGUAIACOL(i)=fGUAIACOL(i)-1; fO3(i)=fO3(i)-1; fPO3GUAIACOL(i)=fPO3GUAIACOL(i)+1; 
 
 
i=i+1;
Rnames{i} = 'MGUAIACOL + O3 = PO3MGUAIACOL';
k(:,i) = 4.00E-19;
Gstr{i,1} = 'MGUAIACOL';Gstr{i,2} = 'O3';
fMGUAIACOL(i)=fMGUAIACOL(i)-1; fO3(i)=fO3(i)-1; fPO3MGUAIACOL(i)=fPO3MGUAIACOL(i)+1; 
 
 
i=i+1;
Rnames{i} = 'MNAPT + O3 = PO3MNAPT';
k(:,i) = 4.00E-19;
Gstr{i,1} = 'MNAPT';Gstr{i,2} = 'O3';
fMNAPT(i)=fMNAPT(i)-1; fO3(i)=fO3(i)-1; fPO3MNAPT(i)=fPO3MNAPT(i)+1; 
 
 
i=i+1;
Rnames{i} = 'SYRINGOL + O3 = PO3SYRINGOL';
k(:,i) = 4.00E-19;
Gstr{i,1} = 'SYRINGOL';Gstr{i,2} = 'O3';
fSYRINGOL(i)=fSYRINGOL(i)-1; fO3(i)=fO3(i)-1; fPO3SYRINGOL(i)=fPO3SYRINGOL(i)+1; 
 
 
i=i+1;
Rnames{i} = 'VANILIN + O3 = PO3VANILIN';
k(:,i) = 4.00E-19;
Gstr{i,1} = 'VANILIN';Gstr{i,2} = 'O3';
fVANILIN(i)=fVANILIN(i)-1; fO3(i)=fO3(i)-1; fPO3VANILIN(i)=fPO3VANILIN(i)+1; 
 
 
i=i+1;
Rnames{i} = 'VGUAIACOL + O3 = PO3VGUAIACOL';
k(:,i) = 4.00E-19;
Gstr{i,1} = 'VGUAIACOL';Gstr{i,2} = 'O3';
fVGUAIACOL(i)=fVGUAIACOL(i)-1; fO3(i)=fO3(i)-1; fPO3VGUAIACOL(i)=fPO3VGUAIACOL(i)+1; 
 
 
i=i+1;
Rnames{i} = 'NAPT + O3 = PO3NAPT';
k(:,i) = 3.01E-19;
Gstr{i,1} = 'NAPT';Gstr{i,2} = 'O3';
fNAPT(i)=fNAPT(i)-1; fO3(i)=fO3(i)-1; fPO3NAPT(i)=fPO3NAPT(i)+1; 
 
 
i=i+1;
Rnames{i} = 'SALAL + O3 = PO3SALAL';
k(:,i) = 2.00E-19;
Gstr{i,1} = 'SALAL';Gstr{i,2} = 'O3';
fSALAL(i)=fSALAL(i)-1; fO3(i)=fO3(i)-1; fPO3SALAL(i)=fPO3SALAL(i)+1; 
 
 
i=i+1;
Rnames{i} = 'CRESOL + O3 = PO3CRESOL';
k(:,i) = 1.94E-19;
Gstr{i,1} = 'CRESOL';Gstr{i,2} = 'O3';
fCRESOL(i)=fCRESOL(i)-1; fO3(i)=fO3(i)-1; fPO3CRESOL(i)=fPO3CRESOL(i)+1; 
 
 
i=i+1;
Rnames{i} = 'DIMPHEN + O3 = PO3DIMPHEN';
k(:,i) = 1.94E-19;
Gstr{i,1} = 'DIMPHEN';Gstr{i,2} = 'O3';
fDIMPHEN(i)=fDIMPHEN(i)-1; fO3(i)=fO3(i)-1; fPO3DIMPHEN(i)=fPO3DIMPHEN(i)+1; 
 
 
i=i+1;
Rnames{i} = 'PHENOL + O3 = PO3PHENOL';
k(:,i) = 1.94E-19;
Gstr{i,1} = 'PHENOL';Gstr{i,2} = 'O3';
fPHENOL(i)=fPHENOL(i)-1; fO3(i)=fO3(i)-1; fPO3PHENOL(i)=fPO3PHENOL(i)+1; 
 
 
i=i+1;
Rnames{i} = 'C5H6 + OH = POHC5H6';
k(:,i) = 9.22E-11;
Gstr{i,1} = 'C5H6';Gstr{i,2} = 'OH';
fC5H6(i)=fC5H6(i)-1; fOH(i)=fOH(i)-1; fPOHC5H6(i)=fPOHC5H6(i)+1; 
 
 
i=i+1;
Rnames{i} = 'M1CYPENT13DIEN + OH = POHM1CYPENT13DIEN';
k(:,i) = 1.07E-10;
Gstr{i,1} = 'M1CYPENT13DIEN';Gstr{i,2} = 'OH';
fM1CYPENT13DIEN(i)=fM1CYPENT13DIEN(i)-1; fOH(i)=fOH(i)-1; fPOHM1CYPENT13DIEN(i)=fPOHM1CYPENT13DIEN(i)+1; 
 
 
i=i+1;
Rnames{i} = 'M5CYPENT13DIEN + OH = POHM5CYPENT13DIEN';
k(:,i) = 1.03E-10;
Gstr{i,1} = 'M5CYPENT13DIEN';Gstr{i,2} = 'OH';
fM5CYPENT13DIEN(i)=fM5CYPENT13DIEN(i)-1; fOH(i)=fOH(i)-1; fPOHM5CYPENT13DIEN(i)=fPOHM5CYPENT13DIEN(i)+1; 
 
 
i=i+1;
Rnames{i} = 'APHELLANDRENE + OH = POHAPHELLANDRENE';
k(:,i) = 3.20E-10;
Gstr{i,1} = 'APHELLANDRENE';Gstr{i,2} = 'OH';
fAPHELLANDRENE(i)=fAPHELLANDRENE(i)-1; fOH(i)=fOH(i)-1; fPOHAPHELLANDRENE(i)=fPOHAPHELLANDRENE(i)+1; 
 
 
i=i+1;
Rnames{i} = 'OTHMONOT + OH = POHOTHMONOT';
k(:,i) = 1.78E-10;
Gstr{i,1} = 'OTHMONOT';Gstr{i,2} = 'OH';
fOTHMONOT(i)=fOTHMONOT(i)-1; fOH(i)=fOH(i)-1; fPOHOTHMONOT(i)=fPOHOTHMONOT(i)+1; 
 
 
i=i+1;
Rnames{i} = 'TERPINOLENE + OH = POHTERPINOLENE';
k(:,i) = 2.20E-10;
Gstr{i,1} = 'TERPINOLENE';Gstr{i,2} = 'OH';
fTERPINOLENE(i)=fTERPINOLENE(i)-1; fOH(i)=fOH(i)-1; fPOHTERPINOLENE(i)=fPOHTERPINOLENE(i)+1; 
 
 
i=i+1;
Rnames{i} = 'CYHEX13DIEN + OH = POHCYHEX13DIEN';
k(:,i) = 1.68E-10;
Gstr{i,1} = 'CYHEX13DIEN';Gstr{i,2} = 'OH';
fCYHEX13DIEN(i)=fCYHEX13DIEN(i)-1; fOH(i)=fOH(i)-1; fPOHCYHEX13DIEN(i)=fPOHCYHEX13DIEN(i)+1; 
 
 
i=i+1;
Rnames{i} = 'EZOCIMENE + OH = POHEZOCIMENE';
k(:,i) = 2.51E-10;
Gstr{i,1} = 'EZOCIMENE';Gstr{i,2} = 'OH';
fEZOCIMENE(i)=fEZOCIMENE(i)-1; fOH(i)=fOH(i)-1; fPOHEZOCIMENE(i)=fPOHEZOCIMENE(i)+1; 
 
 
i=i+1;
Rnames{i} = 'BMYRCENE + OH = POHBMYRCENE';
k(:,i) = 1.01E-10;
Gstr{i,1} = 'BMYRCENE';Gstr{i,2} = 'OH';
fBMYRCENE(i)=fBMYRCENE(i)-1; fOH(i)=fOH(i)-1; fPOHBMYRCENE(i)=fPOHBMYRCENE(i)+1; 
 
 
i=i+1;
Rnames{i} = 'M1CYPENEN + OH = POHM1CYPENEN';
k(:,i) = 8.75E-11;
Gstr{i,1} = 'M1CYPENEN';Gstr{i,2} = 'OH';
fM1CYPENEN(i)=fM1CYPENEN(i)-1; fOH(i)=fOH(i)-1; fPOHM1CYPENEN(i)=fPOHM1CYPENEN(i)+1; 
 
 
i=i+1;
Rnames{i} = 'M2PENT2EN + OH = POHM2PENT2EN';
k(:,i) = 8.75E-11;
Gstr{i,1} = 'M2PENT2EN';Gstr{i,2} = 'OH';
fM2PENT2EN(i)=fM2PENT2EN(i)-1; fOH(i)=fOH(i)-1; fPOHM2PENT2EN(i)=fPOHM2PENT2EN(i)+1; 
 
 
i=i+1;
Rnames{i} = 'C3FURANS + OH = POHC3FURANS';
k(:,i) = 1.32E-10;
Gstr{i,1} = 'C3FURANS';Gstr{i,2} = 'OH';
fC3FURANS(i)=fC3FURANS(i)-1; fOH(i)=fOH(i)-1; fPOHC3FURANS(i)=fPOHC3FURANS(i)+1; 
 
 
i=i+1;
Rnames{i} = 'DIHYMFUR + OH = POHDIHYMFUR';
k(:,i) = 1.32E-10;
Gstr{i,1} = 'DIHYMFUR';Gstr{i,2} = 'OH';
fDIHYMFUR(i)=fDIHYMFUR(i)-1; fOH(i)=fOH(i)-1; fPOHDIHYMFUR(i)=fPOHDIHYMFUR(i)+1; 
 
 
i=i+1;
Rnames{i} = 'OTHFURAN + OH = POHOTHFURAN';
k(:,i) = 1.32E-10;
Gstr{i,1} = 'OTHFURAN';Gstr{i,2} = 'OH';
fOTHFURAN(i)=fOTHFURAN(i)-1; fOH(i)=fOH(i)-1; fPOHOTHFURAN(i)=fPOHOTHFURAN(i)+1; 
 
 
i=i+1;
Rnames{i} = 'M3CYHEXEN + OH = POHM3CYHEXEN';
k(:,i) = 9.61E-11;
Gstr{i,1} = 'M3CYHEXEN';Gstr{i,2} = 'OH';
fM3CYHEXEN(i)=fM3CYHEXEN(i)-1; fOH(i)=fOH(i)-1; fPOHM3CYHEXEN(i)=fPOHM3CYHEXEN(i)+1; 
 
 
i=i+1;
Rnames{i} = 'INDENE + OH = POHINDENE';
k(:,i) = 7.80E-11;
Gstr{i,1} = 'INDENE';Gstr{i,2} = 'OH';
fINDENE(i)=fINDENE(i)-1; fOH(i)=fOH(i)-1; fPOHINDENE(i)=fPOHINDENE(i)+1; 
 
 
i=i+1;
Rnames{i} = 'M2PENTZ13DIEN + OH = POHM2PENTZ13DIEN';
k(:,i) = 1.48E-10;
Gstr{i,1} = 'M2PENTZ13DIEN';Gstr{i,2} = 'OH';
fM2PENTZ13DIEN(i)=fM2PENTZ13DIEN(i)-1; fOH(i)=fOH(i)-1; fPOHM2PENTZ13DIEN(i)=fPOHM2PENTZ13DIEN(i)+1; 
 
 
i=i+1;
Rnames{i} = 'BPHELLANDRENE + OH = POHBPHELLANDRENE';
k(:,i) = 1.70E-10;
Gstr{i,1} = 'BPHELLANDRENE';Gstr{i,2} = 'OH';
fBPHELLANDRENE(i)=fBPHELLANDRENE(i)-1; fOH(i)=fOH(i)-1; fPOHBPHELLANDRENE(i)=fPOHBPHELLANDRENE(i)+1; 
 
 
i=i+1;
Rnames{i} = 'CARENE3 + OH = POHCARENE3';
k(:,i) = 8.51E-11;
Gstr{i,1} = 'CARENE3';Gstr{i,2} = 'OH';
fCARENE3(i)=fCARENE3(i)-1; fOH(i)=fOH(i)-1; fPOHCARENE3(i)=fPOHCARENE3(i)+1; 
 
 
i=i+1;
Rnames{i} = 'PENTE13DIEN + OH = POHPENTE13DIEN';
k(:,i) = 1.01E-10;
Gstr{i,1} = 'PENTE13DIEN';Gstr{i,2} = 'OH';
fPENTE13DIEN(i)=fPENTE13DIEN(i)-1; fOH(i)=fOH(i)-1; fPOHPENTE13DIEN(i)=fPOHPENTE13DIEN(i)+1; 
 
 
i=i+1;
Rnames{i} = 'PENTZ13DIEN + OH = POHPENTZ13DIEN';
k(:,i) = 1.03E-10;
Gstr{i,1} = 'PENTZ13DIEN';Gstr{i,2} = 'OH';
fPENTZ13DIEN(i)=fPENTZ13DIEN(i)-1; fOH(i)=fOH(i)-1; fPOHPENTZ13DIEN(i)=fPOHPENTZ13DIEN(i)+1; 
 
 
i=i+1;
Rnames{i} = 'ETHFURAN2 + OH = POHETHFURAN2';
k(:,i) = 1.08E-10;
Gstr{i,1} = 'ETHFURAN2';Gstr{i,2} = 'OH';
fETHFURAN2(i)=fETHFURAN2(i)-1; fOH(i)=fOH(i)-1; fPOHETHFURAN2(i)=fPOHETHFURAN2(i)+1; 
 
 
i=i+1;
Rnames{i} = 'M2OLFURAN + OH = POHM2OLFURAN';
k(:,i) = 6.18E-11;
Gstr{i,1} = 'M2OLFURAN';Gstr{i,2} = 'OH';
fM2OLFURAN(i)=fM2OLFURAN(i)-1; fOH(i)=fOH(i)-1; fPOHM2OLFURAN(i)=fPOHM2OLFURAN(i)+1; 
 
 
i=i+1;
Rnames{i} = 'FURAN23DIHYD + OH = POHFURAN23DIHYD';
k(:,i) = 4.13E-10;
Gstr{i,1} = 'FURAN23DIHYD';Gstr{i,2} = 'OH';
fFURAN23DIHYD(i)=fFURAN23DIHYD(i)-1; fOH(i)=fOH(i)-1; fPOHFURAN23DIHYD(i)=fPOHFURAN23DIHYD(i)+1; 
 
 
i=i+1;
Rnames{i} = 'M5FURAN23DIHY + OH = POHM5FURAN23DIHY';
k(:,i) = 2.18E-10;
Gstr{i,1} = 'M5FURAN23DIHY';Gstr{i,2} = 'OH';
fM5FURAN23DIHY(i)=fM5FURAN23DIHY(i)-1; fOH(i)=fOH(i)-1; fPOHM5FURAN23DIHY(i)=fPOHM5FURAN23DIHY(i)+1; 
 
 
i=i+1;
Rnames{i} = 'C3PYRROLE + OH = POHC3PYRROLE';
k(:,i) = 1.32E-10;
Gstr{i,1} = 'C3PYRROLE';Gstr{i,2} = 'OH';
fC3PYRROLE(i)=fC3PYRROLE(i)-1; fOH(i)=fOH(i)-1; fPOHC3PYRROLE(i)=fPOHC3PYRROLE(i)+1; 
 
 
i=i+1;
Rnames{i} = 'DHYPYRROLE + OH = POHDHYPYRROLE';
k(:,i) = 1.32E-10;
Gstr{i,1} = 'DHYPYRROLE';Gstr{i,2} = 'OH';
fDHYPYRROLE(i)=fDHYPYRROLE(i)-1; fOH(i)=fOH(i)-1; fPOHDHYPYRROLE(i)=fPOHDHYPYRROLE(i)+1; 
 
 
i=i+1;
Rnames{i} = 'DIMPYRROLE + OH = POHDIMPYRROLE';
k(:,i) = 1.32E-10;
Gstr{i,1} = 'DIMPYRROLE';Gstr{i,2} = 'OH';
fDIMPYRROLE(i)=fDIMPYRROLE(i)-1; fOH(i)=fOH(i)-1; fPOHDIMPYRROLE(i)=fPOHDIMPYRROLE(i)+1; 
 
 
i=i+1;
Rnames{i} = 'ETPYRROLE + OH = POHETPYRROLE';
k(:,i) = 1.32E-10;
Gstr{i,1} = 'ETPYRROLE';Gstr{i,2} = 'OH';
fETPYRROLE(i)=fETPYRROLE(i)-1; fOH(i)=fOH(i)-1; fPOHETPYRROLE(i)=fPOHETPYRROLE(i)+1; 
 
 
i=i+1;
Rnames{i} = 'MPYRROLE + OH = POHMPYRROLE';
k(:,i) = 1.32E-10;
Gstr{i,1} = 'MPYRROLE';Gstr{i,2} = 'OH';
fMPYRROLE(i)=fMPYRROLE(i)-1; fOH(i)=fOH(i)-1; fPOHMPYRROLE(i)=fPOHMPYRROLE(i)+1; 
 
 
i=i+1;
Rnames{i} = 'PYRROLE + OH = POHPYRROLE';
k(:,i) = 1.32E-10;
Gstr{i,1} = 'PYRROLE';Gstr{i,2} = 'OH';
fPYRROLE(i)=fPYRROLE(i)-1; fOH(i)=fOH(i)-1; fPOHPYRROLE(i)=fPOHPYRROLE(i)+1; 
 
 
i=i+1;
Rnames{i} = 'FURAN25DIHYD + OH = POHFURAN25DIHYD';
k(:,i) = 2.25E-11;
Gstr{i,1} = 'FURAN25DIHYD';Gstr{i,2} = 'OH';
fFURAN25DIHYD(i)=fFURAN25DIHYD(i)-1; fOH(i)=fOH(i)-1; fPOHFURAN25DIHYD(i)=fPOHFURAN25DIHYD(i)+1; 

 
i=i+1;
Rnames{i} = 'FURFURAL3 + OH = POHFURFURAL3';
k(:,i) = 4.85E-11;
Gstr{i,1} = 'FURFURAL3';Gstr{i,2} = 'OH';
fFURFURAL3(i)=fFURFURAL3(i)-1; fOH(i)=fOH(i)-1; fPOHFURFURAL3(i)=fPOHFURFURAL3(i)+1; 
 
 
i=i+1;
Rnames{i} = 'OXYFUR + OH = POHOXYFUR';
k(:,i) = 3.50E-11;
Gstr{i,1} = 'OXYFUR';Gstr{i,2} = 'OH';
fOXYFUR(i)=fOXYFUR(i)-1; fOH(i)=fOH(i)-1; fPOHOXYFUR(i)=fPOHOXYFUR(i)+1; 
 
 
i=i+1;
Rnames{i} = 'OXYMFUR + OH = POHOXYMFUR';
k(:,i) = 5.10E-11;
Gstr{i,1} = 'OXYMFUR';Gstr{i,2} = 'OH';
fOXYMFUR(i)=fOXYMFUR(i)-1; fOH(i)=fOH(i)-1; fPOHOXYMFUR(i)=fPOHOXYMFUR(i)+1; 
 
 
i=i+1;
Rnames{i} = 'OXYMCYPENONE + OH = POHOXYMCYPENONE';
k(:,i) = 4.20E-11;
Gstr{i,1} = 'OXYMCYPENONE';Gstr{i,2} = 'OH';
fOXYMCYPENONE(i)=fOXYMCYPENONE(i)-1; fOH(i)=fOH(i)-1; fPOHOXYMCYPENONE(i)=fPOHOXYMCYPENONE(i)+1; 
 
 
i=i+1;
Rnames{i} = 'DIMNAP + OH = POHDIMNAP';
k(:,i) = 7.49E-11;
Gstr{i,1} = 'DIMNAP';Gstr{i,2} = 'OH';
fDIMNAP(i)=fDIMNAP(i)-1; fOH(i)=fOH(i)-1; fPOHDIMNAP(i)=fPOHDIMNAP(i)+1; 
 
 
i=i+1;
Rnames{i} = 'GUAIACOL + OH = POHGUAIACOL';
k(:,i) = 7.53E-11;
Gstr{i,1} = 'GUAIACOL';Gstr{i,2} = 'OH';
fGUAIACOL(i)=fGUAIACOL(i)-1; fOH(i)=fOH(i)-1; fPOHGUAIACOL(i)=fPOHGUAIACOL(i)+1; 
 
 
i=i+1;
Rnames{i} = 'MGUAIACOL + OH = POHMGUAIACOL';
k(:,i) = 9.45E-11;
Gstr{i,1} = 'MGUAIACOL';Gstr{i,2} = 'OH';
fMGUAIACOL(i)=fMGUAIACOL(i)-1; fOH(i)=fOH(i)-1; fPOHMGUAIACOL(i)=fPOHMGUAIACOL(i)+1; 
 
 
i=i+1;
Rnames{i} = 'MNAPT + OH = POHMNAPT';
k(:,i) = 4.86E-11;
Gstr{i,1} = 'MNAPT';Gstr{i,2} = 'OH';
fMNAPT(i)=fMNAPT(i)-1; fOH(i)=fOH(i)-1; fPOHMNAPT(i)=fPOHMNAPT(i)+1; 
 
 
i=i+1;
Rnames{i} = 'SYRINGOL + OH = POHSYRINGOL';
k(:,i) = 8.10E-11;
Gstr{i,1} = 'SYRINGOL';Gstr{i,2} = 'OH';
fSYRINGOL(i)=fSYRINGOL(i)-1; fOH(i)=fOH(i)-1; fPOHSYRINGOL(i)=fPOHSYRINGOL(i)+1; 
 
 
i=i+1;
Rnames{i} = 'VANILIN + OH = POHVANILIN';
k(:,i) = 7.53E-11;
Gstr{i,1} = 'VANILIN';Gstr{i,2} = 'OH';
fVANILIN(i)=fVANILIN(i)-1; fOH(i)=fOH(i)-1; fPOHVANILIN(i)=fPOHVANILIN(i)+1; 
 
 
i=i+1;
Rnames{i} = 'VGUAIACOL + OH = POHVGUAIACOL';
k(:,i) = 7.53E-11;
Gstr{i,1} = 'VGUAIACOL';Gstr{i,2} = 'OH';
fVGUAIACOL(i)=fVGUAIACOL(i)-1; fOH(i)=fOH(i)-1; fPOHVGUAIACOL(i)=fPOHVGUAIACOL(i)+1; 
 
 
i=i+1;
Rnames{i} = 'NAPT + OH = POHNAPT';
k(:,i) = 2.39E-11;
Gstr{i,1} = 'NAPT';Gstr{i,2} = 'OH';
fNAPT(i)=fNAPT(i)-1; fOH(i)=fOH(i)-1; fPOHNAPT(i)=fPOHNAPT(i)+1; 
 
 
i=i+1;
Rnames{i} = 'SALAL + OH = POHSALAL';
k(:,i) = 2.80E-11;
Gstr{i,1} = 'SALAL';Gstr{i,2} = 'OH';
fSALAL(i)=fSALAL(i)-1; fOH(i)=fOH(i)-1; fPOHSALAL(i)=fPOHSALAL(i)+1; 
 
 
i=i+1;
Rnames{i} = 'DIMPHEN + OH = POHDIMPHEN';
k(:,i) = 8.47E-11;
Gstr{i,1} = 'DIMPHEN';Gstr{i,2} = 'OH';
fDIMPHEN(i)=fDIMPHEN(i)-1; fOH(i)=fOH(i)-1; fPOHDIMPHEN(i)=fPOHDIMPHEN(i)+1; 
 
%END OF REACTION LIST

