function k = GC_ALK(M, T,a0, b0, c0, n, x0, y0)
%     ! Used to compute the rate for these reactions:
%     !   IHOO1    + NO =      NO2 + ...
%     !   IHOO4    + NO =      NO2 + ...
%     !   IHP001   + NO =      NO2 + ...
%     !   IHP002   + NO =      NO2 + ...
%     !   IHP003   + NO =      NO2 + ...
%     !   IEPOXAOO + NO =      NO2 + ...
%     !   IEPOXBOO + NO =      NO2 + ...
%     !   ICHOO    + NO =      NO2 + ...
%     !   ISOPNOO1 + NO = 1.728NO2 + ...
%     !   ISOPNOO2 + NO =      NO2 + ...
%     !   IDHNDOO1 + NO =      NO2 + ...
%     !   IDHNDOO2 + NO =      NO2 + ...
%     !   IDHNBOO  + NO =      NO2 + ...
%     !   IDHNDOO  + NO =      NO2 + ...
%     !   INO2B    + NO = 2.000NO2 + ...
%     !   INO2D    + NO =      NO2 + ...
%     !   IHPNBOO  + NO = 1.065NO2 + ...
%     !   IHPNDOO  + NO =      NO2 + ...
%     !   MVKOHOO  + NO =      NO2 + ...
%     !   MCROHOO  + NO =      NO2 + ...
    
    k0 = 2.0E-22 .* exp( n );
    k1 = 4.3E-1 .* ( T ./ 298.0).^(-8);
    k0 = k0 .* M;
    k1 = k0 ./ k1;
    k2 = ( k0 ./ ( 1.0 + k1 ) ) .* 4.1E-1.^( 1.0 ./ ( 1.0 + ( log10( k1 ) ).^2) );
    k3 = c0 ./ ( k2 + c0 );
    k4 = a0 .* ( x0 - T.*y0 );
    k  = k4 .* exp( b0 ./ T ) .* k3;
    %k  = max( [k, 0.0] );
  
end

