% List of other species
% To improve the script, we could do things as followed.
% Change it to nXXX
% Sum up production for lumped compounds.
species_list = {'CH4', 'C2H2', 'C2H4', 'C2H6', 'C3H6', 'BUT1ENE', 'TBUT2ENE', ...
                'CBUT2ENE', 'PENT1ENE', 'HEX1ENE', 'C3H8', 'NC4H10', 'IC4H10', ...
                'NC5H12', 'IC5H12', 'NC6H14', 'M3PE', 'M22C4', 'NC7H16', 'NC8H18', ...
                'NC9H20',  'HCHO', 'CH3CHO', 'C2H5CHO', ...
                'C3H7CHO', 'IPRCHO', 'BUT2CHO', 'C5H11CHO', 'C6H13CHO', 'GLYOX', ...
                'BENZENE', 'TOLUENE', 'PXYL', 'OXYL', 'EBENZ', 'HCOOH', 'CH3CO2H', ...
                'C5H8', 'APINENE', 'BPINENE', 'MACR', 'MVK', 'CH3OH', 'C2H5OH', ...
                'CH3COCH3', 'MEK', 'FURAN', 'M2FURAN', 'M3F', 'DIMEFURAN', 'FURFURAL', ...
                'MEFURFURAL', 'BZFUONE', 'HOCH2CHO', 'DMS', 'ACR', 'MGLYOX', 'PPN', ...
                'ACETOL', 'METHACET', 'ETHFORM', 'IC3H7NO3', 'NC3H7NO3', 'MALANHY', ...
                'C4H6', 'C4ALDB', 'BIACET', 'IC4H9NO3', 'NC4H9NO3', 'ISOPANO3', ...
                'MPRK', 'DIEK', 'PHENOL', 'CATECHOL', 'CYHEXOL', 'BENZAL', 'CRESOL', ...
                'GUAIACOL', 'HEPT3ONE', 'SYRINGOL', 'TM123B', 'IPBENZ', 'PBENZ', 'METHTOL', ...
                'PETHTOL', 'TM135B', 'OETHTOL', 'PINIC', 'PINONIC', 'BCARY', ...
                'ACO2H', 'OXYLOL', 'PBZQONE', 'STYRENE', 'MGUAIACOL', 'OXYLAL'};


species_list = {'HCHO', 'CH3CHO', 'C2H5CHO', ...
                'C3H7CHO', 'IPRCHO', 'BUT2CHO', 'C5H11CHO', 'C6H13CHO', 'GLYOX', ...
                'BENZENE', 'TOLUENE', 'PXYL', 'OXYL', 'EBENZ', 'HCOOH', 'CH3CO2H', ...
                'C5H8', 'APINENE', 'BPINENE', 'MACR', 'MVK', 'CH3OH', 'C2H5OH', ...
                'CH3COCH3', 'MEK', 'FURAN', 'M2FURAN', 'M3F', 'DIMEFURAN', 'FURFURAL', ...
                'MEFURFURAL', 'BZFUONE', 'HOCH2CHO', 'DMS', 'ACR', 'MGLYOX', 'PPN', ...
                'ACETOL', 'METHACET', 'ETHFORM', 'IC3H7NO3', 'NC3H7NO3', 'MALANHY', ...
                'C4H6', 'C4ALDB', 'BIACET', 'IC4H9NO3', 'NC4H9NO3', 'ISOPANO3', ...
                'MPRK', 'DIEK', 'PHENOL', 'CATECHOL', 'CYHEXOL', 'BENZAL', 'CRESOL', ...
                'GUAIACOL', 'SYRINGOL', 'TM123B', 'IPBENZ', 'PBENZ', 'METHTOL', ...
                'PETHTOL', 'TM135B', 'OETHTOL', 'PINIC', 'PINONIC', 'BCARY', ...
                'ACO2H', 'OXYLOL', 'PBZQONE', 'STYRENE', 'MGUAIACOL', 'OXYLAL'};


species_list = {'HEPT3ONE'};

% Loop over each species in the list
for i = 1:length(species_list)
    species_name = species_list{i};
    PlotRatesAvg(species_name, S, 5, 'sumEq', 1, 'unit', 'ppb_h');
    
    % Formulate the output file name
    fileoutput = [prefix, 'figures/', Flight_ID, '_', species_name, '_avgrates_', MECHANISM, FixNOx_postfix, '.png'];

    % Save the figure
    saveas(gcf, fileoutput); % Save the figure
end