#!/bin/bash
#PBS -A UUMM0001
#PBS -N download
#PBS -j oe
#PBS -m abe
#PBS -M jinlx15@outlook.com
#PBS -q regular
#PBS -l walltime=2:00:00
### Request 36 CPUS for 36 threads
#PBS -l select=1:ncpus=1:ompthreads=1:mem=24GB

export TMPDIR=/glade/scratch/$USER/temp
mkdir -p $TMPDIR

source /glade/u/home/$USER/environment/geos_classic_cheyenne.env
#source ~/.cshrc
conda activate gcpy

#Set the proper # of threads for OpenMP
# SLURM_NTASKS ensures this matches the number you set with -n above
export OMP_NUM_THREADS=1 ####$SLURM_CPUS_PER_TASK
export OMP_STACKSIZE=500m
#echo $OMP_NUM_THREADS
python F0AM_dataprocess.py 
